### PR TITLE
Audit dependencies and clean up dependency tree

### LINKED ISSUE #952: Run npm audit checks before v5 rc.1 Releases
I just did a test `npm audit` run on the VM and there are still a lot of vulnerabilities pointed out. Minimally the ones marked as "High" should be fixed before the `rc.1` releases - see also #907. One particular problem is the `mcl-wasm` dependency drawing in a lot of vulnerabilities by having the `nyc` package in the main dependencies, I've opened a PR on this over on the library: https://github.com/herumi/mcl-wasm/pull/17

Apart from that, all libraries should be checked, likely starting with the ones with the fewest internal dependencies (`Common`) and then working up the [dependency tree](https://github.com/ethereumjs/ethereumjs-vm#package-dependency-relationship).

Some practical note: after some trials I came to the conclusion that this is best to be tested "from the outside", to get out of this monorepo hoisting structure as well as to avoid side effects with the `package-lock.json` being present in the repo for CI reasons but not (!) being distributed with the releases, so to do e.g.:

```shell
npm init
npm i @ethereumjs/common (installs the latest beta)
npm audit
```

...within a new directory.

**Library TODO List**

- [x] `@ethereumjs/common`
- [x] `@ethereumjs/tx`
- [x] `@ethereumjs/block`
- [x] `@ethereumjs/ethash`
- [x] `@ethereumjs/blockchain`
- [x] `@ethereumjs/vm`

Final PR date on this: **Wednesday, November 18th** (earlier welcome)

### PR DESCRIPTION
**Pull request by rumkin**
This PR fixes #952 issue to remove vulnerable dependencies from EthereumJS libraries.

#### `@ethereumjs/block`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |

#### `@ethereumjs/blockchain`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |

#### `@ethereumjs/common`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |

#### `@ethereumjs/ethash`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |

#### `@ethereumjs/tx`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 9 | 9 |

- Removed redundant [contributor](https://www.npmjs.com/package/contributor) package. Reason: dependency is not in use.

#### `@ethereumjs/vm`

|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 144 | 0 |

### CODE REVIEW

**Comment by holgerd77** [comment]
@rumkin This looks like a great start on this, cool! 👍 

Two notes:
1) There is the wrong issue linked in the initial comment
2) @herumi was superquick on https://github.com/herumi/mcl-wasm/pull/17 (thanks a thousand times for that 😄  😄 ) and already released versions v0.6.0, v0.7.0 and [v0.7.1](https://www.npmjs.com/package/mcl-wasm) (this should be it now I hope) 😄  on the [mcl-wasm](https://github.com/herumi/mcl-wasm) package without the `nyc` dependency so you can directly take this in here once you are comfortable that other things are working

**Comment by rumkin** [comment]
@holger77 Thanks for reviewing it so quickly!

1. Wrong linked issue fixed.
2. I've tested this with mcl-wasm v0.7.0. Now I've updated this to 0.7.1. So npm audit made with fixed dependencies records in mcl-wasm. I'll commit the latest version of the lib in this PR.

**Comment by holgerd77** [comment]
Short informational note: I've just merged #953 from @evertonfraga which is bringing the `ethereumjs-testing` dependency (respectively mainly the `ethereum/tests` git submodule) into the monorepo. In case if you haven't followed this, if you want to update/rebase your branch on this you need to run:

```shell
cd ethereumjs-vm
npm run bootstrap
git submodule init
git submodule update (takes a while since several 100MB of package size)
```

**Comment by rumkin** [comment]
Rebased changes from #953 through master branch.

**Comment by holgerd77** [comment]
@rumkin have given this a "WIP" label, please change to "PR: Ready for review" label once you consider this ready and - important - also drop a note here, since this label change - won't trigger a separate notification by GitHub.

**Comment by rumkin** [comment]
@holgerd77 Done. It's ready now. I think someone need to reproduce audit independently. I've described actions to be made in the [comment](https://github.com/ethereumjs/ethereumjs-vm/issues/952#issuecomment-727868355) to original issue.

**Review by holgerd77 — APPROVED** [review]
LGTM, can confirm the vulnerabilities on the VM going to 0 on a packaged install, thanks Paul!

**Pull request merged**
