### PR TITLE
Updates to ethereumjs-config v2.0.0 (Cherry Pick Edition 🍒 )

### PR DESCRIPTION
**Pull request by holgerd77**
Replacement PR for #886 

PR cherry-picks the code logic commits from the original PR and add the linting runs as manual commits based upon dedicated `npm run lint:fix` runs. A rebase here was not possible due to the heavy changes along the road e.g. with the block refactor or account removal PRs.

This is WIP, linting is working (apart from one error which can be addressed later). Functionally equivalent currently up to 3b7e6ffd0df3981c3aef2bf0ff128a0b8c66b1be (Ethash linting) with some additional cherry-picks from later commits.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, this is now functionally equivalent to the original PR. 😄 

It would be really nice if someone could pick this up later the day, I will continue a bit but stop soon and @evertonfraga might also not be available today and it would be really good if we can merge this soon.

An in-depth review here is not necessary any more, I already reviewed thoroughly by re-applying the original PR here. I would also pledge that we can merge this (so if you think this is ready: please do!) with the temporary `ethereumjs-config` branch packages still referenced. This is a little thing to update which we can do later and then we have this huge dependecy-creating PR out of the way and can do this on small and a lot more comprehensible steps.

**Comment by evertonfraga** [comment]
Thanks a million, @holgerd77. 

To summarize the problem: 

The old ESLint script had an assumption of a relative path from the package's `package.json` to the dependency, which is not always true in a monorepo setup (consider lerna hoisting, yarn workspaces, etc.)

https://github.com/ethereumjs/ethereumjs-config/pull/26/files#diff-671d995cfc482cb10e88e3165b9be4c6cad8f5166bf17cff8877e6c66b74dfacR3

The [updated script](https://github.com/ethereumjs/ethereumjs-config/blob/master/packages/lint/cli/lint.sh#L3-L32) works locally, but [not on github actions](https://github.com/ethereumjs/ethereumjs-vm/pull/886/checks?check_run_id=1228066331#step:9:12).

Some options we have:
1) ESLint: see if there's any way around it using (or removing) ` --resolve-plugins-relative-to`.
2) Make the path discovery function work with GH actions.

For testing in GH actions, I recommend:
1) pushing to a new branch on `ethereumjs-config` each time, so you don't be subject to any kind of cache
2) updating GitPkg references on our [package.json files](https://github.com/ethereumjs/ethereumjs-vm/pull/886/files#diff-cbe5ece741b6ed0f1506cf97a7242e9167c49020f5e73ce80114a7368da467ffR40-R42).

**Comment by holgerd77** [comment]
Works, jay! 🎉  This is actually the first time I successfully battled with the monorepo CI, a bit proud. 😂

Now we just need to the the `v2.0` releases after merging https://github.com/ethereumjs/ethereumjs-config/pull/39 and then we should be able to merge here.

**Comment by holgerd77** [comment]
Ok, this is ready now. Would be great if this can be reviewed and merged quickly (please just do), so that we have this out of the way and can go on with monorepo related work.

**Review by jochem-brouwer — APPROVED** [review]
Okay, have glanced over this PR and do not see anything alarming. Approved! 😄

**Comment by holgerd77** [comment]
@jochem-brouwer thanks! 😄

**Pull request merged**
