### PR TITLE
Bugfix for opts.state overwrite

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes https://github.com/ethereumjs/ethereumjs-vm/issues/411

### CODE REVIEW

**Comment by holgerd77** [comment]
Should be followed by a bugfix release once merged ASAP, since this is breaking on common API parameter usage.

**Comment by holgerd77** [comment]
Have done.

**Comment by holgerd77** [comment]
(did also do a short manual check if test case really fails on previous version)

**Comment by s1na** [comment]
@holgerd77 Great, thanks!

**Pull request merged**
