### PR TITLE
Update ethereumjs-blockchain to latest

### PR DESCRIPTION
**Pull request by whymarrh**
Refs ethereumjs/ethereumjs-blockchain#92

This PR updates the version of ethereumjs-blockchain we're depending on to the latest, post-TypeScript version.

**Note:** while the above PR is in-progress this will be pointing to a Git URL of my fork. Once the PR is merged (and the tests here will serve as a useful smoke test) this PR will be updated with the correct version on the registry.

### CODE REVIEW

**Comment by whymarrh** [comment]
@holgerd77 I've successfully gotten this PR to test the TypeScript migration. I'll update that PR and bump this one as I adjust the API to minimize breaking changes and update the VM here to use what's changed.

**Comment by holgerd77** [comment]
Cool, congrats!

**Comment by whymarrh** [comment]
As https://github.com/ethereumjs/ethereumjs-blockchain/pull/92 gets closer to the finish line, I've dropped the `files` changes there so this PR so this PR will no longer build correctly.

**Comment by holgerd77** [comment]
@whymarrh Since the blockchain library is now released can you update here (or alternatively just do a new PR if squashing all the commits and general cleaning produces more work after all the updates then just starting fresh)?

**Comment by holgerd77** [comment]
Thanks for the update!

Not sure what's going on with the browser tests, we might need to do some quasi-empty comparison PR or something to see how these behave atm without the changes. Or eventually you can directly debug.

Side note: can you additionally drop a note next time and not just mark this ready for review? One is getting absolutely no notification on this (or can this be adopted?), I just accidentally stumbled upon the update cause I am following you on GitHub and visited GitHub.com. 😜

**Comment by whymarrh** [comment]
> Side note: can you additionally drop a note next time and not just mark this ready for review?

My apologies, I thought that notified the reviewers. I will add a comment as well next time.

**Comment by whymarrh** [comment]
> Not sure what's going on with the browser tests, we might need to do some quasi-empty comparison PR or something to see how these behave atm without the changes. Or eventually you can directly debug.

I too am confused about the `test_api_browser` CI job—I can try debugging it though the CI output is inscrutable.

**Comment by s1na** [comment]
I think the key part is this:

```
29 04 2019 23:46:10.185:WARN [Firefox 66.0.0 (Linux 0.0.0)]: Disconnected (0 times), because no message in 100000 ms.
Firefox 66.0.0 (Linux 0.0.0) ERROR
  Disconnected, because no message in 100000 ms.
```

Maybe its somehow related to [this](https://github.com/ethereumjs/ethereumjs-vm/issues/465#issuecomment-471590496) (also see #468)

**Comment by holgerd77** [comment]
@whymarrh If you work on this (browser test fixing) can you address in a separate PR and not combine with this one? We are generally getting a bit too lazy with mixing up different fixes in combined PRs.

**Comment by holgerd77** [comment]
Have updated this using the `v4.0.1` release PR https://github.com/ethereumjs/ethereumjs-blockchain/pull/118 of the blockchain library for a test run to see if API tests will pass.

Preparation for a release on the `ethereumjs-blockchain` side - do no merge - will update to published release version later.

**Comment by holgerd77** [comment]
This is not really properly testable (at least I didn't find a way to do it) since TypeScript is giving me errors when referencing just the brach and not the release with the type declarations.

I will do it other way around and directly do the release and then update on the final release here.

**Comment by holgerd77** [comment]
@s1na @alcuadrado Ok, this is working now including the API tests. Now ready for a review.

**Comment by alcuadrado** [comment]
> This is not really properly testable (at least I didn't find a way to do it) since TypeScript is giving me errors when referencing just the brach and not the release with the type declarations.

This is not ideal, but you can build the other project, run `npm pack` and extract the generated `.tgz` in this project's `node_modules`.

Maybe git references can be used with one of those special npm scripts. Maybe `postinstall`. Not a big fan of those though. They are pretty obscure.

**Comment by s1na** [comment]
Looks good thanks. Can you maybe also add annotations for other blockchain instances? I saw one in `EEI` and one in `runBlockchain`

**Comment by alcuadrado** [comment]
Same. I saw some in `lib/index.ts`.

**Comment by holgerd77** [comment]
Got the one in `lib/index.ts` and `runBlockchain.ts`. @s1na if there is still one in `EEI` you would have to point me to that, otherwise ready for a re-review.

**Pull request merged**
