### PR TITLE
 Run coveralls on travis

### LINKED ISSUE #269: Enable coveralls for test coverage tracking
See ethereumjs-util as an example how to use coveralls.

Should be run on state tests.

### PR DESCRIPTION
**Pull request by axic**
Fixes #269.

### CODE REVIEW

**Comment by axic** [comment]
State tests cover 93% of `opFns.js`.

**Comment by axic** [comment]
Fun facts:
- apparently there's no division, mod or mulmod by zero :)
- but there is sdiv and smod by zero
- no `sstore` overwriting a non-zero value with a non-zero value
- no test with failed `create` (where the deployment code threw an exception)
- apparently memory increasing?!

All the other missing lines are just cases of covering internal exceptions (creating a trie node failed, etc.)

cc @jwasinger @winsvega

**Comment by axic** [comment]
It is also possible to run multiple tests and combine the coverage files (which we should do).

**Comment by winsvega** [comment]
```no sstore overwriting a non-zero value with a non-zero value```
this definitely happens in some OOG recursive calls

**Comment by holgerd77** [comment]
Very cool PR, also remember to add the badge to the README.

**Comment by axic** [comment]
@holgerd77 should be ok to merge now

**Comment by holgerd77** [comment]
Short note, realized while working on the ``ethereumjs-devp2p`` coverage integration: the [istanbul](https://github.com/gotwarlost/istanbul) package is marked as ``deprecated`` and replaced by [nyc](https://istanbul.js.org/) istanbul CL client.

**Comment by pirapira** [comment]
@axic do you have the new list of missing test cases?  I heard you found some expmod tests for large inputs.

**Comment by axic** [comment]
Using the "new" (15 days old) tests repo is handled in #272.

Currently it fails on a modexp test case with a large input (gas calculation fails because the bignum exceeds 53bits). We haven't yet fixed the code to see the new coverage figures.

cc @jwasinger @cdetrio

**Pull request merged**
