### PR TITLE
BlockHeader: Make BlockOptions param optional

### PR DESCRIPTION
**Pull request by ryanio**
This PR updates the `BlockHeader` factory methods to make the `BlockOptions` param optional.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Doesn't assigning a default value also imply that the argument is optional?

**Comment by ryanio** [comment]
@jochem-brouwer yes in those cases I just wanted to simplify the code a bit, but for the actual important changes see [BlockHeader.fromRLPSerializedHeader](https://github.com/ethereumjs/ethereumjs-vm/pull/932/files#diff-f1ede6d7e271344dfe9b65d51852281d30f70cf3e415e8a15f1c3ab3048240a0R79) and [BlockHeader.fromValuesArray](https://github.com/ethereumjs/ethereumjs-vm/pull/932/files#diff-f1ede6d7e271344dfe9b65d51852281d30f70cf3e415e8a15f1c3ab3048240a0R89) where it was previously required.

**Review by jochem-brouwer — APPROVED** [review]
Yep, looks good to me!

**Comment by ryanio** [comment]
thx!

**Pull request merged**
