### PR TITLE
Only run Coveralls when token exists

### LINKED ISSUE #359: Coveralls CI run fails for PRs from forks
When a PR is done from a fork, coveralls is failing with:

```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

at the end of the state test run, see e.g. https://github.com/ethereumjs/ethereumjs-vm/pull/352.

### PR DESCRIPTION
**Pull request by whymarrh**
Fixes #359

This PR updates the `coveralls` npm script to only run Coveralls when the auth token exists in the environment .

I've also removed the unused Travis CI configuration since that's confusing.

### CODE REVIEW

**Comment by holgerd77** [comment]
Can you do work directly on the main repo? Then it gets possible that a reviewer can eventually directly rebase.

**Comment by whymarrh** [comment]
> Can you do work directly on the main repo? Then it gets possible that a reviewer can eventually directly rebase.

Sure thing, I'll use the main repo for the smaller PRs. That said, I'm more than happy to rebase before merging.

**Comment by holgerd77** [comment]
I think this also makes sense for the larger PRs, we often had the case that someone starts on a feature and then someone else is picking up on the work (due to time constraints of the other person e.g.). Or do you have got some more points on doing this from an own fork?

**Comment by whymarrh** [comment]
I'm not picky. I can work out of the main repo for all PRs.

**Pull request merged**
