### PR TITLE
Support in runBlock runTx options

### PR DESCRIPTION
**Pull request by krzkaczor**
A pretty simple change, just passing forward some options that should be there.

### CODE REVIEW

**Comment by alcuadrado** [comment]
LGTM 👌

**Comment by holgerd77** [comment]
Hi @krzkaczor, can you do a short branch update here?

**Comment by krzkaczor** [comment]
@holgerd77 i just clicked "update branch", is that enough? ;) I thought you can do it too 😆

**Comment by holgerd77** [comment]
@krzkaczor That's enough. 😄 

It is strange, I could do it on this PR https://github.com/ethereumjs/ethereumjs-vm/pull/665 (also submitted from a fork) but couldn't do it here.

If someone has any idea why this is let me know, absolutely clueless, already searched for som e settings on the repo.

**Comment by evertonfraga** [comment]
When creating a PR from an external source, the contributor has the option to allow edits from maintainers. It's a checkbox right below the text field.

**Pull request merged**
