### PR TITLE
Migrate runBlock to typescript

### PR DESCRIPTION
**Pull request by s1na**
Another one bites the dust :smile:

### CODE REVIEW

**Comment by holgerd77** [comment]
@s1na If we target a VM ``v4`` release for next Wednesday (so: in 8 days) do you think this would work out? Is the library in a consistent enough state for this? Would you want to do more changes or is anything immovably outstanding to be done before?

**Comment by holgerd77** [comment]
@s1na @alcuadrado Thought a bit about VM releases yesterday. My idea was that we should now switch a bit the focus and concentrate on ``v4.x`` releases in the coming weeks implementing/adding the approved Istanbul features one-by-one, so that this hopefully gets their way into dev tools early on and people can their hands on that to play around. This could eventually lead to a ``v5`` release wrapping up the final Istanbul state - eventually not necessary though. I would give this whole process roughly a timeframe until August 2018.

Along we continue with refactoring, but now on a more gradual pace, @s1na has actually shifted around A LOT of code. 😋 I would also assume that there might be input from the community on the new structure once we have this out within an official ``v4`` release.

For a ``v6`` release - roughly in October 2018 - we could then wrap up the API changes and expose them, eventually split up the modules and also eventually have this also as an experimental/partly eWASM release, @s1na not sure what your plans with this are and what can be integrated on a stable basis. Continue to work on eWASM VM early on might also help on getting a clearer picture on the API. Once there are two VMs which have to be integrated/talked to it might become easier/more clear to identify the interface structures.

How does this sound?

**Comment by s1na** [comment]
> If we target a VM v4 release for next Wednesday (so: in 8 days) do you think this would work out?

We should be able to do the beta release by then. As you also pointed out in #479 there are some unclear things with the design, but we can solve them gradually. Documentation around the modified parts is also something I'll need to do.

> @s1na has actually shifted around A LOT of code

Yeah, too much. This was a mistake. From now I'll change gears and take a more gradual approach.

The plan sounds good. About ewasm, we'll probably know more in future as the scope of ewasm within ethereum 1.x is not fully clear at the moment.

**Comment by holgerd77** [comment]
@s1na Ok, that sounds like a solid plan. Then let's do a ``beta`` release next Wednesday. Then we have some 1-2 more weeks for final refinement and generally finishing things up and at the same time have a solid ``master`` basis to early on start with ``4.x`` Istanbul implementations without having to do insane rebases towards the new ``TypeScript`` basis.

**Pull request merged**
