### PR TITLE
Integrated testing

### PR DESCRIPTION
**Pull request by evertonfraga**
This PR implements packages integration testing, the Lerna way.

It should be merged to branch `block/release-v3.0.0`.

### CODE REVIEW

**Comment by evertonfraga** [comment]
We have a circular dependency, causing most of the failing jobs.

```shell
ethereumjs-block -> ethereumjs-blockchain -> ethereumjs-block (devDependency)
```

**Comment by holgerd77** [comment]
> We have a circular dependency, causing most of the failing jobs.
> 
> ```shell
> ethereumjs-block -> ethereumjs-blockchain -> ethereumjs-block (devDependency)
> ```

Think this is for testing purposes, now in the monorepo context this might not be as essential as before, eventually you can remove. Might it be a way to run the blockchain tests along block focused PRs?

**Comment by evertonfraga** [comment]
@holgerd77 yes, that's a valid strategy I am considering.

Things that are on the table:
1. As it works locally, find what's the local vs. CI discrepancy and configure it like so.
1. Just move the offending Block and BlockHeader tests to Blockchain, but I wanted to avoid that at first.
1. Given that Blockchain is used basically to reach the parentBlock, I am considering to mock it.

Taking a step back, we should consider to have a `parentBlock: Block` reference in Block, so we could remove `Blockchain` from all function signatures in `Block` and `Header`, as they only serve to fetch the parent block, anyway.

**Comment by holgerd77** [comment]
Great! 😄 This PR changes/updates a lot of things, can you finalize once you are ready with some bullet point list within the initial issue comment, so that nothing get's lost on a release e.g.?

**Comment by evertonfraga** [comment]
@holgerd77 absolutely! There were plenty of changes so far, and I will squash some changes and group them in logical commits, with better descriptions.

**Comment by evertonfraga** [comment]
As a temporary measure for the circular Block <> Blockchain dependency, I have moved `block.spec.ts` and `blockheader.spec.ts` tests to Blockchain and renamed them to "Integration tests", as they never were unit tests, anyway.

Solution TBD, but I'm inclined to mock the Blockchain class with the basic methods the test suite need.

Codecov results have understandably reported lower coverage on Block, but their tests are still being executed.

28 tests successful, 4 failing. We're close :)

**Comment by evertonfraga** [comment]
Superseded by https://github.com/ethereumjs/ethereumjs-vm/pull/734.

**Pull request closed without merging**
