### PR TITLE
Make sure that all accounts are saved before the end of the transaction

### PR DESCRIPTION
**Pull request by jwasinger**
Fixes https://github.com/ethereumjs/ethereumjs-vm/issues/225 .

### CODE REVIEW

**Comment by holgerd77** [comment]
Is this ready for review?

**Comment by cdetrio** [comment]
Can we create a test case for this before merging the fix?

**Comment by jwasinger** [comment]
Ah.  This is a weird one.  I tried to create a test case to cover this but it didn't fail when run through ethereumjs-vm.

My best guess is that, when this scenario occurs in remix/testrpc, the cache is not being flushed properly at the end of the txn, and the account is deleted.

But when run as a state test, somehow this is not the case.

**Comment by axic** [comment]
A few lines above this code is broken:
```
   this.cache.getOrLoad(address, function (err, account) {
     cb(err, account.exists)
   })
```

If `err` is true then `account` should be `null` or `undefined` and this code would dereference it.

**Pull request closed without merging**
