### PR TITLE
Validate stack items after operations

### PR DESCRIPTION
**Pull request by axic**
This helped find some of the bugs already fixed, though it may be useful in the future too.

### CODE REVIEW

**Comment by axic** [comment]
This needs to be updated after #219 (or vice versa).

**Comment by axic** [comment]
I think this will work well after #219 is properly finished and this one rebased.

**Comment by jwasinger** [comment]
I took another look at this one.  Still couldn't figure out what is causing the callback error that we are seeing here.

**Comment by axic** [comment]
@jwasinger probably missed one of the functions since there were so many rebases over 1.5 years :)

**Comment by hugo-dc** [comment]
Hi @axic , @jwasinger , 

I looked at this PR, I found out that SWAP opcode has this configuration:

```javascript
//         name, baseCost, offStack, onStack, dynamic
0x90: ['SWAP', 3, 0, 0, false],
```
onStack is 0, swap opcode returns the swaped element https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L483 , which has to be pushed again to the stack. 

I changed onStack from 0 to 1 for the SWAP opcode, and the failed tests went from 868 to 43.

The remaining failing tests are related to the async opcodes (CALL, CALLCODE, and DELEGATECALL)

**Comment by axic** [comment]
@hugo-dc good find! I think though that `swap` is broken and it shouldn't return the new top stack item. It should just do the stack swap internally (since we don't have a better code base).

**Comment by axic** [comment]
@hugo-dc @jwasinger rebased after the other fix, this should work now?

**Comment by Silur** [comment]
isn't `INTERNAL_ERROR` is relevant in #219 where there was `runState.vmError` having a non enum value exception?

**Comment by hugo-dc** [comment]
@axic I confirm all state tests are passing after the fix 👍

**Pull request merged**
