### PR TITLE
Use typedoc syntax instead of jsdoc, add docs

### PR DESCRIPTION
**Pull request by s1na**
Regarding the names of `Interpreter` and `Loop`:

I think `Interpreter` makes more sense for `Loop` as it reads the bytecode and executes the opcodes. For the current `Interpreter`, the closest concept that comes to my mind is `StateTransition` or `TxExecutor` or `MessageRunner` or something of the like. Another alternative is simply `EVM` which is very general and vague. But I'm hoping others chime in here and come up with better names :)

### CODE REVIEW

**Comment by holgerd77** [comment]
I am very much in favor to then use `EVM` for the outer module (together with the `Loop` -> `Interpreter` renaming), this better prepares for a further separation and is also more transparent for code readers that on the respective place now the inner VM takes over to process. This also leaves more room for further refactoring and thinking about final responsibilities.

Can you go with this and eventually prepare a PR, and also let me know if you plan some further work for today? I would then incorporate all the changes into some finalized release notes tonight (respectively you can also do an update on this, as you prefer).

Then we really should be prepared for a `beta` release tomorrow 😄 (I just last-minute realized that I have to publish with a `--tag beta` tagging. I would follow [this](https://medium.com/@kevinkreuzer/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7) article for publishing, if you have comments on that let me know, haven't done a `beta'  release on npm yet).

**Comment by holgerd77** [comment]
(`runLoop` should likely also be renamed? Just `run`?)

**Comment by s1na** [comment]
Okay then I'll prepare a PR for the renaming. Apart from that I'm not planning any other change for today.

**Comment by holgerd77** [comment]
Cool, thanks.

**Pull request merged**
