### PR TITLE
client: fix undefined BlockHeaders value when syncing

### PR DESCRIPTION
**Pull request by ryanio**
This PR fixes an issue discovered in #1017 when syncing:

```
ERROR [12-16|07:38:59] TypeError: Cannot read property 'map' of undefined
    at BlockFetcher.request (/dev/ethereumjs-vm/packages/client/dist/lib/sync/fetcher/blockfetcher.js:52:31)
```

The `getBlockHeaders` request sometimes returns undefined, for example if the connection times out, so now instead an empty array is returned by default at the end of the caught promise chain.

This PR also:

* updates the `getBlockHeaders.reverse` option value from `number` to `boolean` to better match the API in the blockchain package, and feels more understandable to use.
* updates internal client use of `ethereumjs-devp2p` to `@ethereumjs/devp2p` to use local code changes
* devp2p: makes maxPeers, dpt, and listenPort optional in RLPxOptions (fixes a todo in instantiation in client)

### CODE REVIEW

**Comment by holgerd77** [comment]
Hmm, all tests failing after I have "fixed" a merge conflict, TBH not really sure what's happening on a first look

**Comment by jochem-brouwer** [comment]
I don't think we should call any callback in case that we get an `undefined` (or convert that to an empty array). It doesn't make sense to me, we assume that we receive data, yet if no data is received (or `undefined` data is received) then we still call this callback?

**Comment by ryanio** [comment]
> Hmm, all tests failing after I have "fixed" a merge conflict, TBH not really sure what's happening on a first look

Probably to do with package-lock, I'll check and push up a commit if needed.

**Comment by ryanio** [comment]
> I don't think we should call any callback in case that we get an `undefined` (or convert that to an empty array). It doesn't make sense to me, we assume that we receive data, yet if no data is received (or `undefined` data is received) then we still call this callback?

Well it's a promise so it has to resolve or reject somehow, otherwise it will hang. Returning an empty array when something goes wrong along the way makes sense to me.

**Comment by jochem-brouwer** [comment]
> > I don't think we should call any callback in case that we get an `undefined` (or convert that to an empty array). It doesn't make sense to me, we assume that we receive data, yet if no data is received (or `undefined` data is received) then we still call this callback?
> 
> Well it's a promise so it has to resolve or reject somehow, otherwise it will hang. Returning an empty array when something goes wrong along the way makes sense to me.
> 
> (edit: an empty array is now returned by default at the end of the caught promise chain [d6d042d](https://github.com/ethereumjs/ethereumjs-vm/commit/d6d042de597c1e423a486557f825754313d91f0e))

I have thought a bit about this, would it not make more sense to discard these replies and instead make the peer disconnect if they return `undefined` data (on error) and therefore also making the entire Promise throw? [(this promise)](https://github.com/ethereumjs/ethereumjs-vm/blob/d6d042de597c1e423a486557f825754313d91f0e/packages/client/lib/net/protocol/boundprotocol.ts#L170)

**Comment by ryanio** [comment]
@jochem-brouwer we could make the promise throw, for example it happens [here](https://github.com/ethereumjs/ethereumjs-vm/blob/10000f42ef78261f5401b2715753cb08999ab90f/packages/client/lib/net/protocol/boundprotocol.ts#L154) on timeout, by not catching the promise in the bound method (`BoundProtocol.addMethods`), but then every use would need to ensure a catch clause on the promise otherwise execution may halt, so that's a difficult pattern to enforce everywhere (would be an interesting lint rule to enforce something like this though)

**Review by holgerd77 — APPROVED** [review]
Looks good, I think the throwing promise vs. empty array return case is sufficiently justified for this PR. If there is more need for exchange here just do in the chat with an eventual follow-up PR depending on the outcome of the discussion.

**Pull request merged**
