### PR TITLE
catch errors passing state tests

### LINKED ISSUE #242: circleci tests are broken
It has output like the following, but is still considered "successful":
```
case $CIRCLE_NODE_INDEX in 0) npm run testState ;; esac
Your build output is too large to display in the browser. Only the first 400000 characters are displayed.
Download the full output as a file.

> ethereumjs-vm@2.3.2 testState /home/ubuntu/ethereumjs-vm
> node ./tests/tester -s

TAP version 13
# GeneralStateTests
# file: ContractCreationSpam test: ContractCreationSpam
TypeError: Cannot read property 'map' of undefined
    at parseTestCases (/home/ubuntu/ethereumjs-vm/tests/GeneralStateTestsRunner.js:9:47)
    at runStateTest (/home/ubuntu/ethereumjs-vm/tests/GeneralStateTestsRunner.js:119:21)
    at Promise (/home/ubuntu/ethereumjs-vm/tests/tester.js:232:15)
    at Promise (<anonymous>)
    at testing.getTestsFromArgs (/home/ubuntu/ethereumjs-vm/tests/tester.js:220:16)
    at dir.readFiles (/home/ubuntu/ethereumjs-vm/node_modules/ethereumjs-testing/index.js:30:17)
    at /home/ubuntu/ethereumjs-vm/node_modules/node-dir/lib/readfiles.js:110:34
    at tryToString (fs.js:499:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:487:12)
```

### PR DESCRIPTION
**Pull request by cdetrio**
Fixes #242.

### CODE REVIEW

**Comment by axic** [comment]
Seems to be working, passes the same number of tests as travis:
```
1..4646
# tests 4646
# pass  4646
```

**Comment by axic** [comment]
@cdetrio please rebase

**Comment by holgerd77** [comment]
@cdetrio: for info: rebased this directly on your fork branch, hope that was ok (still had write access on this).

**Comment by holgerd77** [comment]
This is still failing on Circle. If we want to fix this we have to debug the ``Cannot read property 'map' of undefined`` errors occurring on the following line in ``GeneralStateTestRunner``:

```javascript
function parseTestCases (forkConfig, testData, data, gasLimit, value) {
  let testCases = testData['post'][forkConfig].map(testCase => {
     //...
  }
}

**Comment by holgerd77** [comment]
(still not sure though why it is necessary to run the tests both on Travis and on CircleCI, is this an extra security measure? Since this isn't done on any other library?)

**Comment by cdetrio** [comment]
@holgerd77 that error is from using very old test files. Fixed it by logging into CircleCI and clicking "Rebuild without cache".

**Comment by cdetrio** [comment]
btw, thanks for rebasing (access to my branch is enabled by default, "Allow edits from maintainers" github feature).

**Comment by holgerd77** [comment]
@cdetrio Ah ok, then we can generally merge this?

Hope, this error is not triggered again and again on subsequent PRs :-/ so that we would always have to re-trigger this manually, a bit strange that this now occurred again after you already cleared the cache some time ago.

**Comment by cdetrio** [comment]
Yea I thought I rebuilt without cache once before. Anyway, looks ready to me, but I can't review because its my PR.

**Comment by holgerd77** [comment]
Just reviewed, please do the merge.

**Comment by holgerd77** [comment]
Will merge myself, would like to trigger another build afterwards.

**Comment by holgerd77** [comment]
@cdetrio Ah, seems that this caching is now really re-triggered again and again and an old ``ethereumjs-testing`` library is used.

Would it be a way for a fix to switch referencing the ``ethereumjs-testing`` dependency in ``package.json`` by commit like:

```
"dependencies": {
  "ethereumjs-testing": "git://github.com/ethereumjs/ethereumjs-testing.git#15a72e5"
}
```
(see also https://stackoverflow.com/a/18049685)

This would also make testing more reliable and we would have the submodule updates from the testing library a bit better under control without switching again to a sluggish versioned solution.

Does this have any draw-backs?

**Pull request merged**
