### PR TITLE
Validate storage keys' length and improve doc

### LINKED ISSUE #557: StateManager#getContractStorage's buffer sizes
Yesterday I lost 1-2 debugging hours until I realized that `StateManager#getContractStorage`:

1. It expects its `key` parameter to be padded to `32` bytes, and doesn't fail if it has a different size. It just returns something unrelated, most probably, an empty `Buffer`.

2. It can return `Buffer`s of size lower than `32` bytes.

I think these things should, at least, be documented. Or maybe, for (1), it could throw or pad the `Buffer` if needed. For (2), it could pad it. 

I'm more inclined to just throw in (1) and document (2).

### PR DESCRIPTION
**Pull request by alcuadrado**
Closes #557

### CODE REVIEW

**Comment by holgerd77** [comment]
Just a note on first look: "Remove LGTM warning" is not an optimal commit message since this hides the change itself being done and is not really readable in the commit message.

**Comment by holgerd77** [comment]
(sorry, a bit nit-picking, but "Remove unused import in StateManager" or something would just be more expressive).

**Comment by holgerd77** [comment]
@s1na I think these changes/improvements make a lot of sense and would have a tendency to approve and merge (after another PRs CI has been run through and I can update this branch). If you have any objects in between while reading let me know.

**Comment by s1na** [comment]
Looks good to me

**Comment by alcuadrado** [comment]
> Just a note on first look: "Remove LGTM warning" is not an optimal commit message since this hides the change itself being done and is not really readable in the commit message.

That's a good point @holgerd77! I'll write more descriptive commit messages in the future :)

**Pull request merged**
