### PR TITLE
Fix parsing balance in generateCanonicalGenesis

### LINKED ISSUE #586: Genesis stateRoot incorrect for Goerli testnet due to account balances
I have found that when using `vm.stateManager.generateCanonicalGenesis`, where the stateManager is specified for the Goerli testnet, the genesis block stateRoot generated is incorrect. 

The account balance from str -> Buffer in [stateManager](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/state/stateManager.ts#L529) needs some formatting:
```
 account.balance = new BN(initState[address].slice(2), 16).toArrayLike(Buffer)
```

The `initState` account balances from ethereumjs-common is prefixed with '0x' Goerli (not sure if this is a decision for other purposes as they are not for mainnet.

### PR DESCRIPTION
**Pull request by s1na**
Fixes #586

If balances in `ethereumjs-common` are prefixed with `0x`, they'd have to be parsed as a hex string.

Added test cases to ensure generating the genesis state for every chain matches the expected state root. All tests pass, expect for `kovan`. Noticed that the genesisState [file](https://github.com/ethereumjs/ethereumjs-common/blob/master/src/genesisStates/kovan.json) for kovan is empty in ethereumjs-common.

### CODE REVIEW

**Comment by s1na** [comment]
The failing test case would be fixed after https://github.com/ethereumjs/ethereumjs-common/pull/66 is merged and released.

**Comment by alcuadrado** [comment]
I restarted the tests on circle, and I don't get why the tests are failing. https://github.com/ethereumjs/ethereumjs-common/pull/66 was already merged and released.

**Comment by s1na** [comment]
Yeah, I'm wondering too, will look into it now, thanks for restarting the tests

**Comment by s1na** [comment]
Merged in master, should be fixed now

**Comment by s1na** [comment]
I merged the other PR first and this became out-dated. @alcuadrado can you re-approve after tests pass?

**Pull request merged**
