### PR TITLE
Do not deduct value multiple times when using DELEGATECALL

### LINKED ISSUE #82: runCall invoked twice for DELEGATECALL
"When calling a contract function that calls into a library, the Ether sent in the transaction is spent multiple times."

This issue was originally started on testrpc: https://github.com/ethereumjs/testrpc/issues/122 as reported by @graup.

I have narrowed down the issue to `runCall` being invoked twice. It runs once as part of [`runBlock > runTx > runCall`](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runTx.js#L47) and once as part of [`DELEGATECALL > makeCall > runCall`](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L658). 

I assume that the problem is in `DELEGATECALL` since that is doing the library function invocation (the reproducible element). Not knowing more about ethereumjs-vm internals, I am unsure whether `DELEGATECALL` needs to simply remove the `makeCall` invocation or if a subset of makeCall/runCall functionality must be removed. Would like to get input from @tcoulter or someone with more understanding of the codebase before proceeding. Cheers!

### PR DESCRIPTION
**Pull request by axic**
Fixes #82 

Needs tests.

### CODE REVIEW

**Comment by raineorshine** [comment]
This does not fix the problem unfortunately. The send account is still reduced by twice as much as it should.

**Comment by axic** [comment]
@raineorshine @kumavis @tcoulter @mrbodoia pushed a new version - can you please retest?

**Comment by raineorshine** [comment]
Awesome! Excited to try this out. Will try to find time this week.

**Comment by raineorshine** [comment]
Fixed!!! 💯

**Comment by axic** [comment]
@raineorshine cool! Let's add the delegatecall tests into the test suite first and merge this once and for all :)

**Comment by raineorshine** [comment]
@axic Thanks! Are you adding the tests or do you want me to? I tried looking at where to put the tests before and couldn't figure it out, so I might need to be pointed in the right direction if you want me to do that.

**Comment by axic** [comment]
@raineorshine thanks, it is a combination of updated https://github.com/ethereumjs/tests, https://github.com/ethereumjs/ethereumjs-testing and the VM. I think @wanderer is looking into it :eyes:

**Comment by kumavis** [comment]
blocked by https://github.com/ethereumjs/ethereumjs-vm/pull/105

**Comment by cdetrio** [comment]
With all the homestead fixes except this one, there are [32 test failures](http://sprunge.us/ObKF):
```
1..7224
# tests 7224
# pass  7192
# fail  32
```

With this fix, [all tests pass](http://sprunge.us/NAVc):
```
1..7224
# tests 7224
# pass  7224
```

**Pull request merged**
