### PR TITLE
Update and simplify entry example

### PR DESCRIPTION
**Pull request by holgerd77**
This PR updates the entry example from the `examples` folder as well as the README example to run with the latest API changes.

It also makes the example more explicit and simple (taking inspiration from the `tests/api/runCode.js`, thanks again @pinkiebell for this nice structure), hopefully making things more approachable and invite for experimentation.

Along we should also very much have a look at the other examples. These examples are often the main entry point for new users and it is quite some disappointing experience if things are just not working due to outdated example code.

Have also updated the README in the respective example folder with run instructions and tested this for Node and in the browser.

### CODE REVIEW

**Comment by holgerd77** [comment]
Update: have also renamed the example folder to be more fitting on the code run example and also explicitly point out that this is the only example also adding instructions on how to run in a browser (by adding a `-browser` postfix to the folder name).

**Comment by holgerd77** [comment]
Side note: one example I am dreaming of for quite some time is actually one with some guided steps on how to get from your `Solidity` (`Vyper`) code to a code execution in the VM, see also this issue https://github.com/ethereumjs/ethereumjs-vm/issues/277.

Think this would be extremely helpful to people, this is a super-common use case and we should really add.

**Comment by holgerd77** [comment]
@s1na If you can have a short look at this too would be appreciated. Would be good if we constantly work down the open PRs towards the beta release.

**Comment by holgerd77** [comment]
Thanks! 😄

**Comment by holgerd77** [comment]
@s1na @alcuadrado What I would really really love is some other `run-solidity-code` example as mentioned above with some step-by-step instructions to execute a desired function (as simple as possible, likely also mentioning some other tools).

I think this would be super-helpful especially for the `Istanbul` experimentation people will likely want to start, and this is the no. 1 use case / work flow (I would assume) that researchers, Layer 2 implementers,... have their contract using some `Istanbul` relevant functionality (e.g. the guys from Aztech) and want to test how this code behave, see changing gas costs,...

If one of you can come up with some PR on this or just post some suggestions for a workflow so that we can also prepare this for the release that would be superb!

Really think this is some central missing link here! ⛓ 🐔 🥚 😄

**Comment by alcuadrado** [comment]
I'll do it, it should be pretty straightforward, as I've been worked a lot with this kind of stuff in Buidler.

**Comment by holgerd77** [comment]
Cool! 🙂

**Pull request merged**
