### PR TITLE
Add Event Command to Allow Code Injection

### PR DESCRIPTION
**Pull request by seesemichaelj**
Alright @holgerd77 this should be the last major functionality PR I'm going to submit for my [Velma debugger](https://github.com/seeseplusplus/velma) (wow, look at me, I'm already shamelessly plugging my work)...for now at least :grin: I saved the best for last; and by best, I mean the most thought provoking and controversial!

This PR implements an event listener in `runCode.js` with the event name `injectNewCode` (as always, open to name changes).

From the readme description:
The `injectNewCode` event is a command which alters the current executing code (in `runCode.js`). It does not modify the bytecode in storage. It is provided strictly for debuggers to adjust the executing code. An `Object` is provided (e.g. `vm.emit('injectNewCode', data, callback)`) containing the following properties.
- `code`: The new executing runtime bytecode as a hexadecimal string (type `string`)
- `pc`: The new program count to execute at (type `number`)
- `state`: An `optional` object containing other adjustments. If provided, it's properties below are required. (type `Object`)
  - `stack`: The new `runState` stack (type `Array(BN)`)
  - `memory`: The new `runState` memory (type `Array(number)`)
  - `gasLeft`: The new `runState` gasLeft (type `BN`)

-----

This functionality supports the arbitrary code execution within Velma. This is the flow that Velma uses:
1. VM sends step event
1. Breakpoint is hit and therefore execution is paused
1. User inputs some expression in the debug console ind VS Code
1. Velma injects this expression into a new function in the contract source code
1. Velma injects a line to call this function at the current line
1. Velma recompiles the contract
1. Velma injects the runtime bytecode to the VM and program count of the function call
1. Velma continues execution until it steps out of the function, gets the return value, and displays to the user
1. Velma injects the original runtime bytecode and PC to the VM, along with the original stack, memory, and gasLeft, to reset the VM state (minus storage changes, which is acceptable) to before it was called
1. User feels as if they're still at the breakpoint in step 2

I'm fine if there is back and forth on this, while there is no impending deadline, I would at least like to make sure the ball keeps rolling so we have a path forward one way or another.

Let me know what you think! Thanks again for all of your time and support.

### CODE REVIEW

**Comment by seesemichaelj** [comment]
Ah! This one likely should have a test. I'll whip one up; please feel free to review the code as it is however so you can enter the pondering stage :)

**Comment by holgerd77** [comment]
Hi @seesemichaelj, have perceived this but no time to answer yet, will have a closer look next week. Cheers, Holger

**Comment by seesemichaelj** [comment]
Ya I'll get to that early next week when I'm back in town. And no worries! I haven't gotten the chance to write that test I said I would haha

**Comment by holgerd77** [comment]
Hi @seesemichaelj, I am not sure if I will dare to review this from a security perspective since this seems to be highly sensitive, I think at least on mid-term we need a second reviewer here, probably @axic or eventually @jwasinger. My first impression here is that we need to have at least an additional ``allowInboundCommands`` initialization option which is set to ``false`` by default, to only have this explicitly activated if people want to use this, otherwise this seems too dangerous to me.

Step 9) of your list above isn't implemented yet, or do I just not see the corresponding code parts?

**Comment by seesemichaelj** [comment]
Hey @holgerd77!

There definitely is a security concern here, and I'm willing to implement any mechanisms to make it more safe.

I would have definitely preferred to "extend" `ethereumjs-vm` rather than put these hooks deep into the low-level code. However, I could not think of anything that seemed feasible. I'm willing to discuss to brainstorm other methods, but this seemed to be the most practical while minimizing effort.

I'm not seeing (probably because I'm not sure of all the possible use cases of this library) this as being "too dangerous"; I definitely would like to hear elaboration on why this would be too dangerous (i.e. specific instances/use cases).

Step 9) wasn't intended as an `ethereumjs-vm` feature. That was specific to the use case that I'm currently using this feature; it would be the responsibility of the extending library to revert if desired. I could see a potential use case where you would want to change the executing code/state without reverting to the prior code/state. I could implement another event to `revertToStoredCodeAndForkedState`.

Last but not least, there is an alternative to this method which would definitely require more work: instead of adding the ability to change the executing code/runState, have the ability to execute a bytecode sequence in place. It would probably be something like `on('runCode', (bytecode, callback) => {})` where `bytecode` is a hex string of raw code to execute. After the code finished executing, it could return the vmstate for decoding whatever the library needs, and then reset the `runState` `stack`, `memory`, and `gasLeft`

**Comment by holgerd77** [comment]
Could you give a concrete example on what users of your debugger could/would use this for? What kind of code sequence would one want to add? Optimally come up with a concrete scenario.

**Comment by holgerd77** [comment]
Is this all what is described here: https://github.com/seeseplusplus/velma#real-time-debugging ?

**Comment by holgerd77** [comment]
Could you also provide a complete code example how to invoke and use this feature? Maybe you can then also use this for your test.

**Comment by seesemichaelj** [comment]
This feature is specifically to support arbitrary code execution (the second paragraph in the section you referred to, and the GIF below that). Users can call functions and see the result before actually stepping through it, etc. Right now, everything in the GIF uses the functionality that is supported by this PR, but the plan is simple REPL calls for just basic variable lookup (i.e. `t0[2]` from the GIF) and arithmetic would not execute within the VM. However, the GIF shows `doCalc(...)` which actually calls the `doCalc` function in the contract by using the functionality supported by this PR.

So the real scenario users would use this for is: calling arbitrary Solidity expressions (functions/etc) within the context of a breakpoint. A potential scenario would be:
1. User steps over a line which calls 1-to-many functions
1. User looks at result, it isn't what the user expected
1. The user tries different inputs to said function(s) in the debug console/REPL to help debug the issue (perhaps it's an off-by one error, or maybe the inputs were just inherently wrong, but this is one piece of the art of debugging)

Another scenario:
1. User steps over a line which calls 1-to-many functions
1. User looks at result, it isn't what the user expected
1. User restarts debugging session, stops on the line that didn't work
1. Steps into the function(s) and keeps going until some algo is being calculated
1. User tries a different input in the depths of the algo to find a bug in the code

Future scenario (the Velma REPL currently doesn't modify contract local/state variables):
1. User steps over a line which calls 1-to-many functions
1. User looks at result, it isn't what the user expected
1. User restarts debugging session, stops on the line that didn't work
1. User sets the variable being used as an input as the output of some Solidity function with a different input than used in the code
1. User steps over the line to see if the result is better

I will definitely put together a complete code example, along with the test, which should help put this into perspective.

This may take a little, maybe up to a week, until I get the chance to work it alongside my other tasks. It's not high priority (yet haha).

Thanks for working through this and not throwing me out the door quite yet! haha

**Comment by holgerd77** [comment]
This definitely broadens the attack vector, if some malicious code has access to a global VM object and then e.g. causes an online IDE to always display wrong execution results or a block explorer to replay transactions in a falsy way (that's the ones I came up spontaneously but I am sure there is more).

I think if we implement this ``allowInboundCommands`` option this should be ok though. I would just want to prevent that we add unnecessary insecurity to existing users and usages. If people have thought this through and then activate this feature they should be knowing what they are doing and it should be ok.

**Comment by seesemichaelj** [comment]
> I think if we implement this allowInboundCommands option this should be ok though. I would just want to prevent that we add unnecessary insecurity to existing users and usages. If people have thought this through and then activate this feature they should be knowing what they are doing and it should be ok.

I 100% agree with this. Would you also like me to implement the `allowInboundCommands` option? Would you think this is a boolean for all inbound commands or more of an object that specifies specific booleans for different commands? For example:
```
allowedInboundCommands = {
    injectNewCode: true
}
```

**Comment by holgerd77** [comment]
Yes, please add this.

Hmm, for now I would say a simple boolean ``allowInboundCommands`` should be enough (so in this case ``allow`` and not ``allowed`` just to be clear).

**Comment by seesemichaelj** [comment]
I'm closing this issue as I'm not currently maintaining Velma due to a conflict of interest and time commitment with my current job at Truffle Suite. It's very possible this will be revisited when/if arbitrary code execution is on the table for the Truffle Debugger.

Since this PR has some potential security concerns, etc, I will likely not have the time to support this until my day job at Truffle requires it.

Thanks @holgerd77 so much for taking the time to review this and provide feedback (and other PRs)!

**Comment by holgerd77** [comment]
Hi @seesemichaelj, thanks for letting us know and being so transparent about it and actively managing this, really appreciated!

**Pull request closed without merging**
