### PR TITLE
Add Karma browser testing for the API tests

### PR DESCRIPTION
**Pull request by holgerd77**
This PR adds browser API testing to the VM.

It uses a Karma setup similar to the one in the [tx library](https://github.com/ethereumjs/ethereumjs-tx), adds a new npm script command ``testAPI:browser`` and integrates into CI.

This should help prevent issues like https://github.com/ethereumjs/ethereumjs-vm/issues/457. I tested this specific case by injecting the error in a matching test and this would actually break the test run.

There were many files not running through and after some experimenting I decided not to try to fix since this seemed to be too much which would have to be addressed. Instead this PR provides the ground for further fixes by providing an initial list of running + excluded test files in the Karma configuration (``karma.conf.js``). File runs can then fixed case-by-case by opening separate PRs.

One exception to the non-fix approach is that I replaced ``promisify`` in the test files with a fitting [polyfill/shim](https://github.com/ljharb/util.promisify) where it fixed the tests.

### CODE REVIEW

**Comment by holgerd77** [comment]
Had to fix some linting errors and do some CI config modification, but this is now running through and should be ready for review.

**Comment by holgerd77** [comment]
Rebased this.

**Comment by holgerd77** [comment]
@s1na If you could do a short laptop check this would be appreciated, I think it would be nice if we merge early here then this could be already integrated e.g. along https://github.com/ethereumjs/ethereumjs-vm/pull/462.

**Comment by s1na** [comment]
Makes sense. Sorry for not testing in time...

**Comment by holgerd77** [comment]
No problem. 😄

**Pull request merged**
