### PR TITLE
Drop createHookedVm

### PR DESCRIPTION
**Pull request by s1na**
This PR drops support for `createHookedVm` (`hooked.js`) as discussed in https://github.com/ethereumjs/ethereumjs-vm/issues/435.

### CODE REVIEW

**Comment by s1na** [comment]
A dependency of a dependency is failing (see [issue](https://github.com/highlightjs/highlight.js/issues/1984))

**Comment by holgerd77** [comment]
Have crawled a bit through the issue comments, seems a fix is very actively being worked on, there was already one release (which didn't fix). Probably something where one should just wait and not try to work-around (unless there is something really simple).

This is coming from ``documentation`` -> ``highlight.js``, just for some context.

**Comment by s1na** [comment]
Yeah seems to be nearly fixed.

A similar scenario has happened a couple of times so far. What do you think about anchoring dependencies to an exact version (i.e. not semver equivalent versions like `^8.1.2` or `~8.1.21). But then there should probably be a more regular dependency upgrading (either manually or via greenkeeper).

**Comment by holgerd77** [comment]
Hmm, fixing ``documentation`` wouldn't have solved having the new ``highlight.js`` version installed in this case, would it? Not sure if going tighter with dependencies is a solution here since we already have problems catching up on the current setup with all the dependencies.

**Comment by holgerd77** [comment]
Anyhow, this doesn't happen too often I would say, but we can keep an eye on.

**Comment by holgerd77** [comment]
Have done some branch update here for re-testing. I have also added ``npm install highlight.js@9.14.2`` as CircleCI pre-dependency command project setting. However Circle is saying that these settings no longer apply so probably won't work.

**Comment by holgerd77** [comment]
Ah. Don't work.

**Comment by holgerd77** [comment]
Have rebased this.

**Comment by holgerd77** [comment]
@s1na Since [tests/api/index.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/api/index.js) tests are running with Karma and should also test this case, I would say it has now become save enough to merge here?

**Pull request merged**
