### PR TITLE
Handle balance overflow as evm exception

### PR DESCRIPTION
**Pull request by cgewecke**
**Revival of #676** 

Includes review fixes by @evertonfraga 

Addresses #672.

Have made a minimal reproduction of #672 at [cgewecke/checkpoint-repro][1]. It runs two transactions vs. ganache-core:
 + the first overflows an account balance and errors as expected with `Value overflow`
+ the second fails with `Cannot get state root with uncommitted checkpoints`, indicating that the previous tx has left the vm in an unresolved state.

This happens because the balance overflow error is thrown directly from `evm._executeCall` and `evm._executeCreate` without being handled via the revert/commit steps in the method which calls them ([evm.executeMessage][2])

PR
+ returns `Value overflow` exceptions as part of the vm result (instead of throwing), similar to the way contract creation address collisions are [handled][3]
+ makes `Value overflow` a VMError
+ modifies the existing overflow test to inspect the result error and verify that the checkpoint count is 0 when runTx completes
+ adds a balance overflow test for contract creation txs

**NB:** Looks like [invalid precompiles][4] also trigger an uncontrolled throw ([here][5]). Haven't addressed that but if this PR is the correct approach, perhaps that could be resolved here as well. 

[1]: https://github.com/cgewecke/checkpoint-repro
[2]: https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/evm/evm.ts#L117-L143
[3]: https://github.com/ethereumjs/ethereumjs-vm/blob/fdfdf33d99f59f272e9833bed77b42c19eb2942b/packages/vm/lib/evm/evm.ts#L197-L206
[4]: https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/evm/evm.ts#L338-L341
[5]: https://github.com/ethereumjs/ethereumjs-vm/blob/fdfdf33d99f59f272e9833bed77b42c19eb2942b/packages/vm/lib/evm/evm.ts#L172

### CODE REVIEW

**Comment by cgewecke** [comment]
codecov is erroring on  a negative diff change but I don't see one. Not sure what's happening there.
```
codecov/project — 90.98% (+-0.01%) compared to 7eb3217
```

**Comment by evertonfraga** [comment]
Codecov uses a [quite confusing notation](https://docs.codecov.io/docs/codecov-delta) for coverage. There are two metrics:

The **codecov/patch** check refers only to the changes we made, and that's fully covered:

image

The **codecov/project** check compares to the parent commit, which is usually `master`, but in this case, your previous commit.

image

I assume that was just a rounding error, the change looks 👌 and there are tests for it.

**Comment by holgerd77** [comment]
@evertonfraga if possible we should also add some pragmatic thresholds here for CodeCov (this was at least possible for Coveralls), so to allow for minor decreases (like 0.5% or so, eventually a bit less) together with some absolute threshold not be allowed to fall below.  These little decreases occur all the time (e.g. on 1-2 liner PRs without tests, rewriting little things/splitting stuff up for clarity,...). This gets annoying without some basic flexibility.

**Comment by evertonfraga** [comment]
Yes! I have just described tweaking config in this issue: https://github.com/ethereumjs/ethereumjs-vm/issues/723

**Pull request merged**
