### PR TITLE
Integrate ethereumjs testing logic

### PR DESCRIPTION
**Pull request by holgerd77**
This PR integrates the code logic from `ethereumjs-testing` into the VM test runner, see https://github.com/ethereumjs/ethereumjs-testing/issues/48 for reasoning.

It also fixes the file permissions for the `state-test-run-test.sh` test runner state test config test file (before it was not executable) and adds a new initialization and test runner start output box to make configuration options and test running conditions more transparent, the following are some output examples:

```shell
$ node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=spuriousDragon
+--------------------------------------------------+
| VM -> BlockchainTests                            |
|                                                  |
| TestGetterArgs                                   |
| skipTests           : 54                         |
| forkConfig          : EIP158                     |
|                                                  |
| RunnerArgs                                       |
| forkConfigVM        : spuriousDragon             |
| forkConfigTestSuite : EIP158                     |
+--------------------------------------------------+

$ ts-node ./tests/tester --state --test=CreateCollisionToEmpty --jsontrace
+--------------------------------------------------+
| VM -> GeneralStateTests                          |
|                                                  |
| TestGetterArgs                                   |
| skipTests           : 54                         |
| forkConfig          : Istanbul                   |
| test                : CreateCollisionToEmpty     |
|                                                  |
| RunnerArgs                                       |
| forkConfigVM        : istanbul                   |
| forkConfigTestSuite : Istanbul                   |
| jsontrace           : true                       |
+--------------------------------------------------+
```

A useful follow-up PR on this would be to actually rework the integrated code and use a more modern async directory traversal logic like e.g. outline [here](https://stackoverflow.com/a/45130990) on StackOverflow.

### CODE REVIEW

**Comment by evertonfraga** [comment]
I guess this is blocked until we find out how to reuse this logic on other packages. Putting a label so it doesn't risk being merged for now. :)

**Comment by holgerd77** [comment]
@evertonfraga ah no it is not, the VM is the only consumer of this

**Comment by holgerd77** [comment]
@evertonfraga ah no, you're right, sorry. Have to rethink about this.

**Comment by holgerd77** [comment]
After letting this sink in for a couple of days I still wonder if we should give up on this code being on the `ethereumjs-testing` library and rather move to the libraries which need access to the `tests` submodule. Most parameters on the `ethereumjs-testing` functions are customized to be used for the VM anyhow. If we would integrate the there used functionality into the tx library e.g. code logic would likely be a lot simpler, especially with more modern async code structures for reading directories and files. So this will likely not cause that much code redundancy. And on most libraries where this code was once used we already switched to static test fixtures copied over from `ethereum/tests` anyhow - see e.g. this PR https://github.com/ethereumjs/ethereumjs-block/pull/61 - to avoid the heavy load of the submodule and with the reasoning that tests apart from the VM tests over on `ethereum/tests` very rarely change (often no change in years).

On the VM side we would have a much tighter integration and the unnatural code separation would fall away (currently no one is really overly motivated to do dedicated `ethereumjs-testing` releases just for some code changes) and there is a good chance that this will directly benefit our CI/test performance efforts, since then we can then experiment a lot easier with different code structures on test run parallelization.

Thoughts?

Likely not be able to further participate in the discussion (holidays), but if there is an agreement maybe just merge here as a starting point - then one can further improve on the code directly on the VM - and we can - for now - just leave the code as well in the `ethereumjs-testing` repository.

**Comment by jochem-brouwer** [comment]
I agree with moving this logic to the VM, see also [this comment](https://github.com/ethereumjs/ethereumjs-vm/pull/815#discussion_r462620415).

**Comment by holgerd77** [comment]
@evertonfraga @jochem-brouwer Since Jochem is also supporting this idea do we want to merge this in here so that Jochem can build upon the changes done here on his testing update work (mentioned above)?

I think we can also live with the situation to keep this in some hybrid state and have the `ethereumjs-testing` logic kept there for some releases if necessary.

Have solved the merge conflicts on this branch (`nyc` needed to go back to v12 along some PR change from Everton).

**Pull request merged**
