### PR TITLE
API Tests for runBlockchain

### PR DESCRIPTION
**Pull request by s1na**
This is part of the PR series for adding API tests to the vm:

* Adds `iterator` to `fakeBlockchain` to facilitate testing
* Fixes a minor issue for propagating errors in `runBlockchain`
* Adds tests for `runBlockchain`, considering the new API with `blockchain` moving out of `stateManager`.

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Sina, can you execute runBlockchain() from within a VM context (so vm.runBlockchain()) here and not by a standalone require?

**Comment by s1na** [comment]
Hey Holger. Sure thing. I was trying to use mocks as much as possible in the individual modules, and then use real objects in the tests for `index`, as here [this](https://github.com/ethereumjs/ethereumjs-vm/pull/315/commits/cac3e5384c2651c437fb14bd7f36d6eadf7bc3d2#diff-9679ea269cd4379e5469309afc2f7bcb).

**Comment by holgerd77** [comment]
Ah okay, if this follows some overall concept, it should be ok

**Comment by holgerd77** [comment]
Hi @s1na, sorry, I am a bit delayed on reviews due to personal reasons. If you are getting impatient or stuff, you can always drop me a note - maybe as a pm on Gitter - then I try to re-sort some priorities.

**Comment by s1na** [comment]
Hey @holgerd77, I totally understand and there's no hurry on my side ;)

**Comment by holgerd77** [comment]
Hi @s1na, if I run the tests from this PR locally with ``node tests/api/runBlockchain.js``, 2 out of 4 of the tests are failing:

```shell
TAP version 13
# runBlockchain
# should run without a blockchain parameter
# should run without blocks
# should run with genesis block
ok 1 genesis should be set for blockchain
# should run with valid and invalid blocks
ok 2 block3 should be the current head
not ok 3 should have returned error
  ---
    operator: fail
    at: Test.t.test (/Users/hdrewes/Documents/DEV/EthereumJS/ethereumjs-vm/tests/api/runBlockchain.js:70:10)
  ...
not ok 4 test exited without ending
  ---
    operator: fail
  ...

1..4
# tests 4
# pass  2
# fail  2
```

Maybe it would be best to first update https://github.com/ethereumjs/ethereumjs-vm/pull/327 to include the new tests in the tests and coverage suite (have a look at my comment over there if you can go along with the suggested changes) and rebase this on top. Then we have an explicit feedback here directly in the CircleCI test run if the new tests are passing.

**Comment by s1na** [comment]
@holgerd77 I think the failing tests might be due to https://github.com/ethereumjs/ethereumjs-blockchain/pull/60. They were passing for me locally due to my mistake of modifying `ethereumjs-blockchain` in `node_modules` and then forgetting to revert the changes...sorry.
When I tried to update `ethereumjs-blockchain` manually to 3.2.0, another issue resurfaced. I created a [PR](https://github.com/ethereumjs/ethereumjs-blockchain/pull/64) for it. Hopefully afterwards, the `runBlockchain` tests should pass.

**Comment by holgerd77** [comment]
Hi Sina, I've now added the API tests to the CircleCI tests (we somewhat forgot about that) with this https://github.com/ethereumjs/ethereumjs-vm/pull/347 PR.

I also released your fix on the blockchain library as [v3.2.1](https://github.com/ethereumjs/ethereumjs-blockchain/releases/tag/v3.2.1).

Would be good if you could now rebase this on top of this, then we can see more transparently what is going on and if this can be merged.

**Comment by holgerd77** [comment]
Ah, sorry, my fault. The VM actually generally is not yet updated to the ``ethereumjs-blockchain``3.x series, this is actually in the working on https://github.com/ethereumjs/ethereumjs-vm/pull/325. This should be merged soon.

**Comment by holgerd77** [comment]
It would be probably good if you undo the latest commit and then rebase again once the PR mentioned above is merged. //cc @vpulim

**Comment by holgerd77** [comment]
Did the respective changes in the PR from above.

**Comment by s1na** [comment]
From `Restore node_modules cache`:

```
No cache is found for key: v1-node-pull/336-mbSU64mYTrWWbsyhoNqPw4O1kp7BMwKRG7Xhh_pobE0=
Found a cache from build 1631 at v1-node-pull/336-
```

It could be that circleci is falling back to a previous `node_modules` cache, and is not actually using the most recent dependencies to run the tests.

**Comment by holgerd77** [comment]
I just removed and fetched your updated branch and tested locally, this has the same 4 failing tests as shown in the CircleCI log (you have access to that, or haven't you?), so this should be relatively certain something in the tests or the tests discovering an implementation issue.

**Comment by holgerd77** [comment]
Ah interesting. I am not understanding deeply enough what is going on, do you think we should permanently keep the cache changes from your temporary commit?

**Comment by s1na** [comment]
@holgerd77 I'm also not sure, but I think the worst that can happen is that circleci will take longer in some cases (like this PR), because it will need to re-install dependencies.

**Comment by holgerd77** [comment]
Do you know if this cache is also applying for the test runs itself (so that e.g. state tests are not re-run)? This would eventually be a pity, since we could loose a lot of test performance here.

Is there also a possible key combination like ``v1-node-{{ checksum "package.json" }}`` without the branch referenced? Intuitively I would assume that this might be some middle ground to not waste too much cache performance gains.

**Comment by s1na** [comment]
This cache is only for `node_modules` I think.

That's a good point, as long as the checksum of `package.json` is the same, it shouldn't make a difference which branch it is, right? So are you suggesting replacing this key, with what you mentioned, or having that as fallback?

```yaml
keys:
    - v1-node-{{ .Branch }}-{{ checksum "package.json" }}
    - v1-node-{{ checksum "package.json" }}
```

or only the second key?

**Comment by holgerd77** [comment]
At a first look at https://circleci.com/docs/2.0/caching/, the keys seems pretty flexible to compose. Yes, can you remove your last commit and try the two-key-version, with a commit message without the "tmp" part, then we can maybe directly take this if it turns out to work.

**Pull request merged**
