### PR TITLE
New testStateDev test run command to allow for parallel Constantinople testing

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by holgerd77** [comment]
@axic Ok, this would allow for in-parallel Constantinople test runs.

There is no way of adding ``Constantinople`` to the ``supportedHardforks`` list if tests should be able to run. In my opinion this is ok if it's clearly documented. If you don't like that, there is still the alternative that people have to re-add this on every Constantinople PR, which would be more inconvenient (at the end it would have to be removed again before merging), but possible.

**Comment by holgerd77** [comment]
@axic No way of "not adding" of course, have updated this in the comment.

**Comment by holgerd77** [comment]
@axic Hmm, I think I'll rename this from ``test_state_dev`` to ``test_state_constantinople``, then it is more transparent why this is failing and we don't have to re-explain this all the time to external contributors.

**Comment by axic** [comment]
I guess we can select `test_state_constantinople` as allowed to fail in github.

**Comment by axic** [comment]
I see that's already done. I think the only comment is that I'd rename `test_state` to `test_state_byzantium`.

**Comment by holgerd77** [comment]
Review done informally by @axic, merged.

**Pull request merged**
