### PR TITLE
Add promise support to all public functions

### PR DESCRIPTION
**Pull request by dmihal**
After the discussion in #253, I decided to take a different approach with promisifying the API

### CODE REVIEW

**Comment by holgerd77** [comment]
Thanks for the new PR, haven't thought longer on this, but one thing to consider here is:
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

If I get this right, the current implementation is killing parts of ``V8`` optimization, which wouldn't be acceptable.

**Comment by dmihal** [comment]
@holgerd77 Interesting article, I'm giving the whole thing a read-through!

I've updated the promisify function to follow the guidelines and maintain optimization.

**Comment by holgerd77** [comment]
@dmihal Have you seen/also considered this: http://2ality.com/2017/05/util-promisify.html ?

**Comment by dmihal** [comment]
@holgerd77 Updated the code to integrate with util.promisify, much cleaner now.

**Comment by whymarrh** [comment]
@dmihal would you mind rebasing this PR on the latest `master` so that we can re-evaluate these changes with a (hopefully) passing build? (Or wait for #402 and rebase then, either works.)

**Comment by holgerd77** [comment]
I was always relatively skeptical on this since it introduces such somewhat hacky stuff at core pieces of the library. @whymarrh Do you think you can safely judge the implications on this? Also already think along a bit if this effects somehow a future ``TypeScript`` transition.

Could someone also provide some concrete usage example of the new API invocation? I assume the "old" version stays untouched with this, is this correct?

**Comment by whymarrh** [comment]
The concept here is a safe one if less ideal than just using Promises directly: if a callback is given it's used for continuation, if not a Promise is returned. This won't really affect a future transition to TypeScript as this API is expressible with types.

> Could someone also provide some concrete usage example of the new API invocation? I assume the "old" version stays untouched with this, is this correct?

Yup, all existing usages of the API should be unchanged. Examples of the concept using simple functions:

**Old**

```js
runCode(opts, function () {
    // Do stuff
})
```

**New**

```js
await runCode(opts)
// Do stuff
```

Like I said, it's certainly less ideal than just having a promise-only API but this is a non-breaking change.

**Comment by holgerd77** [comment]
Superseded by #546, will close.

**Pull request closed without merging**
