### PR TITLE
[EXPERIMENT] Build library as an es5 module with rollup and ES6 modules

### PR DESCRIPTION
**Pull request by Firescar96**
Following discussion from https://github.com/ethereumjs/ethereumjs-vm/pull/248, but this time made a separate branch

I didn't change the version number, but this would be a patch level or minor version change. Someone else should make a suggestion.

Update (from @holgerd77): For current production usage this was replaced by https://github.com/ethereumjs/ethereumjs-vm/pull/281 (see discussion). PR will remain open for experimentation with rollup/``ES6`` modules.

### CODE REVIEW

**Comment by axic** [comment]
As discussed in the previous PR can you please split this into multiple commits and PRs?

There are a lot of different changes mixed into one. (See my comments on the previous one for potential parts which should be separate.)

**Comment by Firescar96** [comment]
For the four comments:
- I fixed the first comment, different files use different capitalization and that property is maintained.
- second comment This pull request converts `require` statements to `import` statements, but `import` statements are required to be at the top of the file by the project standards checker -> the section has to be rewritten. The functionality is exactly the same though, just in a shorter syntax.
- for the last two, that change to the tests is undone

**Comment by holgerd77** [comment]
@Firescar96 Thanks for republishing, will setup this locally in the upcoming days and play a bit with the rollup bundling and dist generation, still have to get a bit more comfortable/familiar with this.

**Comment by holgerd77** [comment]
@yann300 Hi Yann, are you around and could give a short opinion on this PR? I would really like to hear something about it from Remix/Libraray User side.

**Comment by holgerd77** [comment]
@benjamincburns Would be interested on your opinion on this too.

**Comment by benjamincburns** [comment]
Thanks for asking, @holgerd77. I'm not opposed to this, provided babel is working fine.

That said, I might be missing something, but I don't see the value of switching from `require` to `import` at this point. It feels a little like change for change's sake to me.

**Comment by Firescar96** [comment]
@benjamincburns I read some docs to figure out the difference between ES6 modules via 'import` and legacy modules via `require`
https://www.quora.com/What-are-the-benefits-of-using-ES6-modules-import-and-export-statement
https://rollupjs.org/guide/en
https://github.com/rollup/rollup

And why rollup:
https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/
https://survivejs.com/blog/rollup-interview/

and there is something about es6 modules (not exactly sure what) that allows rollup to do a flat build structure instead of wrapping modules in functions and allows for tree-shaking

**Comment by yann300** [comment]
Hi @holgerd77 having ES5 build seems ok to me. Please ping us in the remix channel when this is going to be on the release, so we can run it against remix tests.

**Comment by axic** [comment]
Is there any way we can avoid having the `dist` file in the repo? It blows up the git repo size significantly (git cannot deduplicate based on chunks).

**Comment by Firescar96** [comment]
sure, I could add something like this to the package.json file: https://github.com/d3/d3/blob/master/package.json#L33 so the build/dist folder is only generated before deploying the npm package

I think it would be a separate pull request

**Comment by holgerd77** [comment]
I did a similar thing with the ``ethereumjs-util`` ``ES5`` PR just being merged
https://github.com/ethereumjs/ethereumjs-util/pull/114/files

I think the ``files`` directive I added to ``package.json`` probably isn't even necessary, since the ``main`` directive is already referencing the ``dist/index.js`` file.

I don't like the idea of having another PR for that, otherwise we would drag the ``dist/index.js`` file into the repo and out again, and this would be an integral part of this PR anyhow. Can you directly add/change this here? Or is there another reason I am not seeing to make this separate?

**Comment by holgerd77** [comment]
@benjamincburns Yes, see the answer from @Firescar96 and the previous thread on https://github.com/ethereumjs/ethereumjs-vm/pull/248, this leads to a much-much leaner build.

**Comment by holgerd77** [comment]
@yann300 Ok, thanks for the answer, will do.

**Comment by holgerd77** [comment]
@benjamincburns Do you see any disadvantages in moving to ``ES6`` import syntax?

**Comment by Firescar96** [comment]
Okay, I got the sense from previous comments from axic that there is a preference for PRs that change as little as possible. If you don't mind the build change here, then I don't either.

**Comment by holgerd77** [comment]
@Firescar96 Generally yes, but in this case I think it makes sense to do this here.

**Comment by Firescar96** [comment]
I added the same prepublish steps as ethereumjs-util

**Comment by holgerd77** [comment]
@Firescar96 Ok, cool! Can you run the ``bundle`` task in ``package.json`` also for the ``coverage`` task:

```
"coverage": "npm run bundle && istanbul cover ./tests/tester.js -- -s",
```

I think this should fix the travis build issue.

**Comment by Firescar96** [comment]
The version of `instanbul`  added in a recent commit is deprecated: https://github.com/gotwarlost/istanbul and will never support es6 making the tests fail.
I ported to the newer version of the same library, 'nyc'.

**Comment by benjamincburns** [comment]
@holgerd77 & @Firescar96 sorry it's taken me a while to get back to you both - was traveling.

Like I said before I'm not opposed to the change, and I wouldn't trust my opinions on this matter as well-formed; I really don't have a very deep understanding of ES 6.

I don't see this causing any harm for ganache or truffle, so it's all good by me :+1:.

**Comment by holgerd77** [comment]
There is one problem with ``coveralls`` here, the files from the ``tests`` folder are now also included in the coverage report: https://coveralls.io/builds/15471724 leading to coverage decrease (compare e.g. https://coveralls.io/builds/15514133).

Will also see if I find some time to look into this later, you can also try or write if you're seeing the cause.

**Comment by holgerd77** [comment]
Just had a look through the generated ``dist`` code, this looks pretty (relatively) untouched and very clean.

**Comment by holgerd77** [comment]
@Firescar96 Just having a look through the rollup configuration, for the ``rollup-plugin-commonjs`` it is mentioned on the GitHub [README](https://github.com/rollup/rollup-plugin-commonjs) that usage mostly takes place together with [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve), which is not included here.

Is this intentional?

**Comment by holgerd77** [comment]
@Firescar96 Coveralls is still not working, experimented a bit:

```
nyc --exclude ['tests/**'] node ./tests/tester -s
```

This should work and suffice.

**Comment by holgerd77** [comment]
@Firescar96 Ok, I manually tested the ``rollup`` build with including the ``rollup-plugin-node-resolve`` plugin and compared the resulting ``dist`` files with linux ``diff`` command, which showed actually no differences, so files are identical.

If you can drop a node on this anyhow would be happy nevertheless, not getting this completely yet.

**Comment by holgerd77** [comment]
Just reading this for context: https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c

What I'm just grasping right now is that Node is not supporting ``ES6`` modules natively. This would mean that we are not able any more to use the code "natively", go to the Node console and directly do a ``const VM = require('./lib/index.js')``.

Have to let this sink in, nor sure if we are willing to pay that price respectively how important that is? @axic @cdetrio @jwasinger

**Comment by holgerd77** [comment]
Some more context, ES6 module browser support:
https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/

**Comment by holgerd77** [comment]
"Using ES modules natively in Node.js": http://2ality.com/2017/09/native-esm-node.html

**Comment by holgerd77** [comment]
Actually I am doing this all the time: copy-pasting the ``require`` statements from a file in the Node console, and the do interactive testing. Hmm. 😒

**Comment by Firescar96** [comment]
You can still run your test code from a file or import from the `dist` folder.

**Comment by Firescar96** [comment]
It's been about a month since I opened the original PR for this and it solves the original issue. If there isn't anything else wrong with it I'd like for it to be merged. Every other concern that has been brought up has been addressed and the general opinion about it seems to be positive.

**Comment by holgerd77** [comment]
Sorry, it's not that easy. From the core development team it's actually only @axic and me who made comments, @axic rather neutral, I addressed concerns. I won't merge this light-heartedly, and 4 weeks isn't actually that long (in our pace 😄 🐌 ), there are many PRs from current team members which take a lot longer until merged.

Unfortunately many devs are occupied with eWASM stuff atm. @cdetrio @jwasinger @axic could you please have a look at this and give an opinion?

**Comment by axic** [comment]
It seems that somehow this change messes up code coverage. Have a look at "coveralls" link in the "Some checks were not successful".

**Comment by Firescar96** [comment]
How about a I submit a PR for building this library using babel before it gets published to npm? The files would be larger, but it wouldn't break your development style.

**Comment by holgerd77** [comment]
Yes, that's what I actually also wanted to suggest know. We were already in the process of doing this for other libraries, e.g. https://github.com/ethereumjs/ethereumjs-util/pull/114

If you want, you can prepare this, otherwise I could also do a PR on this still within this week.

We can keep this PR for experimentation. Maybe when Node has been matured more regarding ``ES6`` module support, we can come back to this, still find the prospect of the lower build size a strong argument to continue to keep an eye on this.

**Comment by Firescar96** [comment]
If you're doing that for other libraries then you should make the PR for this one.

**Comment by holgerd77** [comment]
@Firescar96 Ok, should be ready: https://github.com/ethereumjs/ethereumjs-vm/pull/281
Can you do a review / give an opinion if this solves your build problems?

**Comment by Firescar96** [comment]
Looks good. :+1: 

Onto the next library, I'm getting the same errors from https://github.com/ethereumjs/ethereumjs-tx and https://github.com/MetaMask/provider-engine

**Comment by holgerd77** [comment]
@Firescar96 Ok, ``ES5`` babel PR https://github.com/ethereumjs/ethereumjs-vm/pull/281 is now merged, please give this a couple of days until we do a new release here.

Will also prepare a similar PR for ``ethereumjs-tx``. I have got no insight on the ``provider-engine`` library, so you probably want to directly get in touch over there with @kumavis or @benjamincburns.

**Comment by holgerd77** [comment]
@Firescar96 Ah, just had a look. The ``ethereumjs-tx`` library actually is already distributed [being transpiled](https://github.com/ethereumjs/ethereumjs-tx/blob/master/package.json) with babel to ``ES5``. What kind of errors do you get there?

**Comment by holgerd77** [comment]
I now actually tried ``create-react-app`` for the first time, cloned the repo and added the ``ethereumjs-tx`` library ``v1.3.3``, added the example code to the ``app.js`` file and did some output of serialized tx data on the app screen started with ``npm start``:

bildschirmfoto 2018-03-06 um 11 23 12

This actually worked without errors so far.

**Comment by Firescar96** [comment]
You're right, ethereumjs-tx is updated. `provider-engine` is using an old version of `ethereumjs-tx`.

Thanks for working with me on this for so long!

**Pull request closed without merging**
