### PR TITLE
[WIP] Introduce modexp precompile (EIP101)

### PR DESCRIPTION
**Pull request by axic**
Implements https://github.com/ethereum/EIPs/pull/198.

### CODE REVIEW

**Comment by axic** [comment]
This needs to be updated, but will be needed for metropolis support.

**Comment by axic** [comment]
The message format and the gas formula has changed substantially in the EIP.

**Comment by holgerd77** [comment]
Hi @axic, will you have time to update this pull request for the ``Byzantium/Metropolis`` release within the next 2-3 (?) weeks? Or does someone else have to take on the job?

**Comment by axic** [comment]
Superseded by #161.

**Pull request closed without merging**
