### PR TITLE
Upgrade karma dependencies to latest

### PR DESCRIPTION
**Pull request by ryanio**
This PR originally tried to fix an intermittent ci error in karma for `block` where the firefox launcher timed out before starting, but was fixed in #868.

This PR now just updates the karma dependencies to latest as a housekeeping task, and adds a chrome browser runner to the tx package.

**package-locks:** since we use [hoisting](https://github.com/lerna/lerna/blob/master/doc/hoist.md), all package node_modules are brought to the root, so the packages do not need package-locks anymore. the only exception is vm which is using one version prior of nyc for a compatibility issue, which may be resolved in the future.

### CODE REVIEW

**Comment by evertonfraga** [comment]
Our current CI system depends on the `package-lock.json` to generate cache keys for each package. [Reference](https://github.com/ethereumjs/ethereumjs-vm/blob/master/.github/workflows/block-build.yml#L35).

Without a `package-lock.json`, the hash gets compromised and bad cache is saved:

1. [Cache miss](https://github.com/ethereumjs/ethereumjs-vm/pull/861/checks?check_run_id=1078523636#step:4:7).
2. [Cache saved with bad key](https://github.com/ethereumjs/ethereumjs-vm/pull/861/checks?check_run_id=1078523636#step:18:3).

On a following run, if the hash is the same, even though you had changed dependencies, it will place the old dependency files in node_modules

**Comment by evertonfraga** [comment]
Block tests passed, so I've triggered another run.

**Comment by ryanio** [comment]
@evertonfraga thanks for that explanation for the package-locks. so what would be the correct way to regenerate updated package-locks for all packages?

**Comment by evertonfraga** [comment]
This should do:
```
lerna exec rm package-lock.json
npm i
```

**Comment by evertonfraga** [comment]
FF test failed again. @ryanio did you see any evidence of such bug on Karma packages, that would be fixed by upgrading versions, or is that a "black-box" approach?

**Comment by ryanio** [comment]
@evertonfraga no I didn't find anything in the updates that fixed it, i was hopeful, but doesn't seem to have resolved.

i think regardless would be nice to give all the deps a bump, i also added a firefox runner for tx package

**Comment by evertonfraga** [comment]
I'm betting on concurrency with the Chrome tests. It has a low timeout of 2s by default, and it's not a generous one when it comes to running things on CIs.

**Review by holgerd77 — APPROVED** [review]
Nice, some further simplifications for the tx karma setup, looks good!

**Pull request merged**
