### PR TITLE
Support external statemanager in VM constructor

### LINKED ISSUE #33: StateManager Should be public
It would be nice to expose the StateManager publically. And split it into its own module. What should the API be?

### PR DESCRIPTION
**Pull request by axic**
Fixes #33.

### CODE REVIEW

**Comment by axic** [comment]
@kumavis do you think this is enough to solve #33?

@yann300 this should also simplify Remix's code.

**Comment by holgerd77** [comment]
Probably will already ease things. I have a bit the fear, that the API remains too implicit, if ``StateManager`` is still coupled with the VM and not documented explicitly. Would it still be worth the work/pursue the idea to publish this as a separate module like proposed by @wanderer in the issue #33 description?

Just started to wrap my head around this though, so have not formed an opinion myself on this.

**Comment by axic** [comment]
The goal of this is to make it less error prone for those who already modify it to do so. State manager should be cleaned up and/or redesigned but that may take a while (forever?). Probably a good middle ground is having this patch, but marking `opts.stateManager` as `EXPERIMENTAL` so that we can make breaking changes to the statemanager API as we do not commit to the current one.

**Comment by axic** [comment]
@holgerd77 added a bold `EXPERIMENTAL` warning to it.

@jwasinger please reapprove if still happy

**Pull request merged**
