### PR TITLE
CALL to other contracts within a contract

### PR DESCRIPTION
**Pull request by kvhnuke**
Currently CALL doesnt automatically add the code for sub contract calls, this PR will add the contract code if account is a contract

### CODE REVIEW

**Comment by jwasinger** [comment]
Hi @kvhnuke, CALL is already implemented here:

https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L488-L556

**Comment by jwasinger** [comment]
> Currently CALL doesnt automatically add the code for sub contract calls
Can you elaborate on this

**Comment by axic** [comment]
I don't think this is needed because `makeCall` will load up the destination account. It is done in `callcode` and `delegatecall` because those execute different code over an account.

Why is this needed @kvhnuke ?

**Comment by kvhnuke** [comment]
hi @axic 
Im super sorry it was my stupid mistake I was working on cache hook and passing hex values instead of buffers.

**Comment by axic** [comment]
No worries!

**Pull request closed without merging**
