### PR TITLE
Update ethereumjs-tx library to v2.0.0

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by s1na** [comment]
Could you also maybe add type annotations for txes (e.g. https://github.com/ethereumjs/ethereumjs-vm/blob/e13503b97c4922e3222f36c6510fb3e182475d58/lib/runTx.ts#L23)?

**Comment by holgerd77** [comment]
@s1na I'm a bit unsure on this, here is a code snippet from `runTx.ts`, is this correct (still no `TypeScript` guru), or is there a "lighter" way to do it?

```TypeScript
import { Transaction } from 'ethereumjs-tx'
import VM from './index'
import Bloom from './bloom'
import { default as Interpreter, InterpreterResult } from './evm/interpreter'
import Message from './evm/message'
import TxContext from './evm/txContext'
import PStateManager from './state/promisified'
const Block = require('ethereumjs-block')

/**
 * Options for the `runTx` method.
 */
export interface RunTxOpts {
  /**
   * The block to which the `tx` belongs
   */
  block?: any
  /**
   * A [`Transaction`](https://github.com/ethereum/ethereumjs-tx) to run
   */
  tx: Transaction // TODO: Update ethereumjs-tx
}
```

Does this mean we have to move the `ethereumjs-tx` dependency to the main dependencies?

**Comment by s1na** [comment]
Hmm, we could add the `ethereumjs-tx` type declaration file manually to the VM to avoid adding a dependency, but that means it'd have to be updated after every change.

Should we maybe just add it as a dependency? it's very likely that the users would need it anyway (specially when using `runTx`).

**Comment by holgerd77** [comment]
Hmm, think declaration redundancy is not a good thing.

Probably adding as dependency seems fine since we already have block and blockchain in the main dependencies, more consistent like this anyhow. Will get better/more flexible again once we extract `evm` as an own module.

Will add and update the PR soon.

**Comment by holgerd77** [comment]
Ok, have updated, this is now ready for review. I really think this makes a lot of sense to have this in the main dependencies, this makes it a lot clearer what tx version we currently support here.

@s1na I just found one annotation missing (the one you mentioned). You wrote "e.g.", did I miss some other place(s)?

**Comment by holgerd77** [comment]
Update: oh, good that we switched, this is actually throwing various errors now, like:

```shell
lib/runTx.ts:152:51 - error TS2551: Property 'from' does not exist on type 'Transaction'. Did you mean '_from'?

152   const txContext = new TxContext(tx.gasPrice, tx.from)
                                                      ~~~~
```

**Comment by holgerd77** [comment]
@alcuadrado Ah, `TypeScript` doesn't allow me to switch the access to the now protected `_from` attribute. What was/is actually the reason to `_from` [now being protected](https://github.com/ethereumjs/ethereumjs-tx/blob/master/src/transaction.ts#L37) while other similar class members like `gasLimit`, `to`,... being publicly accessible?

If you have a clear path going forward with this I would appreciate if you directly do, I originally wanted to focus on other tasks (release notes VM e.g.).

**Comment by s1na** [comment]
> I just found one annotation missing (the one you mentioned). You wrote "e.g.", did I miss some other place(s)?

Only that one came to mind then. I don't think there are any other places.

Regarding the `_from` field, it should be possible to use `getSenderAddress`.

**Comment by holgerd77** [comment]
@s1na Ah, thanks, missed that method, will update the PR over on the VM side accordingly.

**Comment by holgerd77** [comment]
Ah, we are on the VM side, lol. 😛

**Comment by holgerd77** [comment]
Waiting for https://github.com/ethereumjs/ethereumjs-tx/issues/163 before an update here.

**Comment by alcuadrado** [comment]
> Waiting for [ethereumjs/ethereumjs-tx#163](https://github.com/ethereumjs/ethereumjs-tx/issues/163) before an update here.

I created https://github.com/ethereumjs/ethereumjs-tx/pull/166

**Comment by holgerd77** [comment]
Updated this, ready for review.

**Comment by s1na** [comment]
Update: after merging #469, there was a conflict in `package.json`. Fixed that (in browser via github :smile:), so we can merge this too.

**Pull request merged**
