### PR TITLE
[WIP] Run with the latest tests

### PR DESCRIPTION
**Pull request by holgerd77**
Updated ethereumjs-testing to v1.2.0 (submodule 428842e)

### CODE REVIEW

**Comment by holgerd77** [comment]
Very modest result, one new failing test:
``ecmul_0-3_5616_28000_96``

**Comment by holgerd77** [comment]
Just rebased this.

**Comment by axic** [comment]
Fails on:
```
# file: ecmul_0-3_5616_28000_96 test: ecmul_0-3_5616_28000_96
not ok 4554 the state roots should match
  ---
    operator: equal
    expected: |-
      '631a600601a67ef3357813281d417e141e5eddf306abd4d8824bdc141536e3c6'
    actual: |-
      '261abab5092a666776b6e956e2d572769b5cfef2fcff383ae956fcc75e36e133'
    at: replenish (/home/circleci/project/ethreumjs-vm/node_modules/async/dist/async.js:998:17)
  ...
```

**Comment by axic** [comment]
This may be fixed with my update to rustbn.js to use ethereum-bn128.rs?

**Comment by holgerd77** [comment]
@axic No, not fixed. Same test ``ecmul_0-3_5616_28000_96`` failing.

**Comment by holgerd77** [comment]
Rebased this, mainly for the reason to have this also run with the Constantinople tests for a first impression (see https://github.com/ethereumjs/ethereumjs-vm/pull/317).

**Comment by holgerd77** [comment]
Will remove the rustbn.js commit, this is breaking the build.

**Comment by axic** [comment]
> Will remove the rustbn.js commit, this is breaking the build.

The reason it was breaking is because it pointed to a branch (PR), but that was merged and deleted. Lets try again with master.

**Comment by axic** [comment]
While the precompile cleanup doesn't fix the problem, I think they should be merged. Created #318.

**Comment by axic** [comment]
Debugging the ecmul issue locally.

**Comment by axic** [comment]
In the test case the input data is

`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330644e72e131a029b85045b68181585d2833e84879b9709143e1f593f000
00000000000000000000000000000000000000000000000000000000000000000000`

And rustbn.js returns empty output, which means it considers it a failure.

**Comment by axic** [comment]
@holgerd77 we would need to update our test repo after https://github.com/ethereum/tests/pull/477. I would like to verify if the bitwise stuff still works.

**Pull request closed without merging**
