### PR TITLE
devp2p monorepo transition

### PR DESCRIPTION
**Pull request by holgerd77**
This PR transitions the [ethereumjs-devp2p](https://github.com/ethereumjs/ethereumjs-devp2p) library to the monorepo, partly addresses #892 

Ok, this should hopefully do it, transition is inspired by the [monorepify](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/monorepify.sh) script from Everton, I used a simple version though and extracted the commands useful for this transition and for the main part followed the instructions from [this post](https://medium.com/@filipenevola/how-to-migrate-to-mono-repository-without-losing-any-git-history-7a4d80aa7de2) linked in the script.

Git history is preserved, I tested a merge on my own fork here https://github.com/holgerd77/ethereumjs-vm. [Commit history](https://github.com/holgerd77/ethereumjs-vm/commits/master) looks like things are put into proper order, see also e.g. [here](https://github.com/holgerd77/ethereumjs-vm/commit/77625aadf11d27522c8e9209092b8cf4590f08ac) for an example commit diff. This should be the main thing, if there are smaller caveats - some CI, dependency, link stuff to fix - we can also do post-merge.

Also updated the following:

- Moved CI config to root, adjusted to monorepo structure
- Adjusted dependency versions in `package.json` for hoisting
- Updated local `README` links
- Updated monorepo `README` sections

Please nevertheless do not merge directly, I would do tomorrow (CET) in case of successful reviews. I would wait for 2+ reviews on this before merge.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, CI is passing. 😄 

Ready for review, I would ask you to not demand further rebases on this since this is delicate with these merged Git histories, not worth for consolidating on a few extra commits.

**Comment by jochem-brouwer** [comment]
I checked the commits which you built upon the current master branch of the package, which look good to me. However, [git history](https://github.com/ethereumjs/ethereumjs-vm/commits/monorepo-add-devp2p/packages/devp2p/src/eth/index.ts) does not seem to be viewed correctly. Maybe [this has to do with it?](https://github.com/ethereumjs/ethereumjs-vm/pull/971/commits/d435b055a3f694fb40bd5957278d167eff23dc40)

**Comment by ryanio** [comment]
@jochem-brouwer github has some issues showing history across renames, see https://github.com/isaacs/github/issues/900

**Comment by jochem-brouwer** [comment]
Wow it seems like GitHub should add a high priority to this feature. I don't understand how this is not a thing yet! I recall that I ran into this problem as well to track the `prioritizedTaskExecutor` changes in MPT.

**Comment by ryanio** [comment]
yeah it's a bummer 😕 i'm also surprised they haven't allocated more resources toward it, i would find it useful multiple times per week, especially with the monorepo and also all our js=>ts file renamings. gitlab shows it properly...ev imported the monorepo in gitlab once to test that his script modified the git history correctly and it looked nice.

**Comment by holgerd77** [comment]
Any chance that this still gets an approval tonight, or do you guys have further reservations? Then I could directly tackle the client transition tomorrow as some follow-up.

**Review by ryanio — APPROVED** [review]
yes LGTM!

**Comment by holgerd77** [comment]
@ryanio thanks 😄 , @jochem-brouwer (or @cgewecke) please give this an additional approval when you are confident here as well.

**Comment by jochem-brouwer** [comment]
Ah yes sorry I wanted to check this, this afternoon.

```
git fetch
git checkout origin/monorepo-add-devp2p
cd packages/devp2p/src
git log --follow eth
```

Output

```git
commit 37597e7ca13884e06fc32679e709d935300609a6 (HEAD, origin/monorepo-add-devp2p)
Author: holgerd77 <Holger.Drewes@gmail.com>
Date:   Mon Nov 30 14:19:58 2020 +0100

    devp2p -> monorepo transition: fixed linting

commit d435b055a3f694fb40bd5957278d167eff23dc40
Author: holgerd77 <Holger.Drewes@gmail.com>
Date:   Mon Nov 30 12:02:57 2020 +0100

    monorepo preparation: moved all files to packages/devp2p
```

This should show the commit history, right?

**Comment by cgewecke** [comment]
@jochem-brouwer 

If I checkout this branch and use simple `git log`,  I can see early devp2p commits interleaved in the history.

For example, somewhere below the ORIGIN/HEAD master commit, I find this, (part of this PR).
```
commit 77625aadf11d27522c8e9209092b8cf4590f08ac
Author: holgerd77 <Holger.Drewes@gmail.com>
Date:   Fri Nov 20 09:40:01 2020 +0100

    eth64: minor fixes
```

Are you expecting (or seeing) something else?

**Review by cgewecke — APPROVED** [review]
LGTM :tada:

**Comment by evertonfraga** [comment]
Great job, @holgerd77!

@jochem-brouwer yes, the `--follow` should do the trick. Or for specific/annoying cases, you can push the repo to gitlab, and you'll have a history that actually makes sense 🙈

I didn't check, but please make sure the tests for devp2p are present on the newly added node-versions CI file.

**Comment by evertonfraga** [comment]
Also, if you want to update the diagram, you can click on the URL at line 35 of the README.md ([Mermaid chart](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgdm17Vk19XG4gIGNvbW1vbiAtLT4gYmxvY2tjaGFpblxuICBjb21tb24gLS0-IGJsb2NrXG4gIGNvbW1vbiAtLT4gdm1cbiAgY29tbW9uIC0tPiB0eFxuICBldGhhc2ggLS0-IGJsb2NrY2hhaW5cbiAgYmxvY2sgLS0-IGJsb2NrY2hhaW5cbiAgYmxvY2tjaGFpbiAtLT4gdm1cbiAgYmxvY2sgLS0-IHZtXG4gIHR4IC0tPiB2bVxuICB0eCAtLT4gYmxvY2tcbiAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX19)). 

Then, add the package reference to devp2p, copy the SVG code and the new bug URL into the README.

**Comment by holgerd77** [comment]
One note here: when I wanted to pull this into my local `master` branch, git wanted to do a merge commit, which I found a bit spooky. I then did a backup copy of my current working repo and did a fresh clone, everything seems to be working fine though.

**Comment by jochem-brouwer** [comment]
@cgewecke yes the commits are in the commit log, but if I try to track where these devp2p files originated from by `git log --follow <file>` then these commits somehow do not show up 🤔

**Comment by holgerd77** [comment]
For me locally they actually do 🤔, e.g. `git log --follow ../devp2p/tsconfig.json`:

Bildschirmfoto 2020-12-01 um 12 33 47

**Comment by jochem-brouwer** [comment]
Yes you are right @holgerd77, I called this on a directory which did not exist in the original `devp2p` repo, so it makes sense it doesn't show old commits there. I just checked and indeed if you call it on a file, it follows it just fine! 😅  Will also approve.

**Review by jochem-brouwer — COMMENTED** [review]
Approved

**Pull request merged**
