### PR TITLE
Dropping ethereumjs-testing dependency

### PR DESCRIPTION
**Pull request by evertonfraga**
Dropping the git submodule within a dependency is fundamental to the Yarn workspaces PR #900.

- [x] Add git submodule pointing to ethereum/tests
- [x] CI: Add git submodule on checkout instructions 
- [x] Refactor tests VM
- [x] Refactor tests Tx
- [x] Remove all references to ethereumjs-testing on the code
- [x] Remove all references to ethereumjs-testing on the docs
- [x] Add error handling with message to load the `git submodules`
- [x] Documentation for contributors

### CODE REVIEW

**Comment by ryanio** [comment]
would it be possible to run the needed `git submodule init; git submodule update` commands as an install hook?

**Comment by evertonfraga** [comment]
@ryanio it's something to think about: if we want to make the installation process to download more than 1GB worth of test files.

Given it's only used in VM and Tx tests, I believe the best would be to have an npm script, like [`pretest`](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts) that checks the submodule out before each of those libraries test runs :)

**Review by holgerd77 — APPROVED** [review]
This looks good, great, thanks Everton! 😄 

(man, I already miss you)

**Comment by holgerd77** [comment]
I just set this up locally - everything works - but I was getting a bit nervous since I realized post-merge that we are moving away - at least regarding the state of this PR - from versioning the submodule state by doing [ethereumjs-testing](https://github.com/ethereumjs/ethereumjs-testing/releases) releases on a concrete submodule commit state and therefore working on a stable state of the `ethereum/tests` repo.

I am actually totally puzzled that the tests here are passing beside this update, the `ethereum/tests` state we had freezed in the `ethereumjs-testing` [v1.3.3](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.3.3) release and the current `develop` state are several months apart and on such `ethereum/tests` updates we always had something breaking in the VM in the past, so this would be a total primer if everything "just passes". 😄  Or - to not exclude any possibility - might this be some caching thing and in reality the old submodule state was used? 🤔  (just to think in all directions).

Anyhow: I am a bit unsure about this. In the past just going along with `develop` led to an unstable development and CI situation. On the other hand if we change the process here and just go along we can also provide much quicker feedback to the `ethereum/tests` guys, and are also always up with the latest tests, both might be beneficial for us internally as well as the overall test development situation.

What do others think? Is this worth a try? Or should we remain conservative here and reintroduce some static snapshot referencing (@evertonfraga would this still be possible within the current directly integrated submodule structure?)?

**Comment by holgerd77** [comment]
Also: would this blow some CI stuff if we would have the folder in `packages`? Otherwise I would find this significantly more beautiful.

**Comment by evertonfraga** [comment]
Hey! 

The `git submodule` documentation and usage are a bit misleading, but a submodules are always locked to a commit reference. I actually don't understand why the branch name is ever present on the `.gitmodules` file. 

image

To lock it to the same commit `ethereumjs-testing` is using, please do: 

```
cd ethereum-tests
git checkout 66a55cd42f63845e34767504d0a7a62b452a7e7a
cd -
git add ethereum-tests
```

Now, as for moving the submodule, newer versions of git support the same syntax as regular files:

```
git mv ethereum-tests packages/ethereum-tests
```

The following step would be to change file references to the `./packages` directory, which should be straightforward (`tests/testLoader.ts` in both tx and vm).

The CI should work out of the box.

**Pull request merged**
