### PR TITLE
Refactor test runner

### PR DESCRIPTION
**Pull request by holgerd77**
Long overdue refactoring of the test runner. Sorry, this was such a mess and there was so much interdependent to correct that I gave up on keeping the changes separate and put everything in one commit. Hope this is somewhat reviewable. This should also proof to a greater extend correct if the CI runs pass, I will keep this in draft state for some more days and also do some more local failure case testing + testing of CL parameters and report back here.

PR does the following:

- Promisification of test runners + (most) of the util functions
- Separate config in `tests/config.js`
- Broader code cleanup
- Removal of `VMTests` since not being used for years and being deprecated now for some time on `ethereum/tests`
- Removal of `async` library usage (some missing in `util.js`)
- Update: fixed a bug where exceptions in blockchain tests went unnoticed, these now either failed or are compared to an eventually present `expectException[FORKNAME]` field in the test file
- Adds two shell scripts for manually testing CI options for blockchain and state tests
- Temporarily add (extremely extensive) `ForkStressTest` blockchain test to skipped tests, should be addressed in a separate PR

### CODE REVIEW

**Comment by evertonfraga** [comment]
All green! 
 Cleaning old code and modernizing it was much needed.

**Comment by holgerd77** [comment]
Phew, did a lot of CI runs on this. I think I now have got it, will give a last ok once all the tests pass. I rolled back on promisification of util.setupPreconditions since this caused selected failures on all test types (API, StateTests, BlockchainTests) and I couldn't draw conclusions on the underlying root cause. So this can be tackled separately eventually.

The last failed test runs of the blockchain tests were actually some previously hidden failure runs by passing on errors in places like [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/BlockchainTestsRunner.js#L145) but never do anything with it. I have now fixed this, this was happening on a lot of test where there were `expectException[FORKNAME]` fields in the test files, so in the current run these errors are now detected and will pass if such a field is present in the test file.

**Comment by holgerd77** [comment]
Ok, finally. All VM tests pass (I think the Block test failure can be safely ignored, this is just due to some GH Actions outage likely). So this is now ready for review. 😀

I added two additional tests to the skip list, these were exposed by the `expectException` feature integration and can/should be handled separately.

I also added two simple scripts for manually testing/triggering various CL options for testing the test runner a bit more systematically.

**Comment by holgerd77** [comment]
Some more notes:

The command executions from the two scripts pass apparently.

The test exception declaration awareness is rather just a start than a final integration. At some point it might be worth to have a closer look again here if exceptions are actually thrown within an appropriate context and handled appropriately. Should nevertheless be some working ground for this round here.

**Comment by ryanio** [comment]
looking great 🎉 added a small commit to remove the `test:vm` package.json script

**Comment by holgerd77** [comment]
@ryanio Thanks 😉, can you already give an approval or do you want to wait a bit longer?

**Pull request merged**
