### PR TITLE
Update docs to latest

### PR DESCRIPTION
**Pull request by ryanio**
This PR runs `lerna run docs:build` to update docs to latest.

### CODE REVIEW

**Comment by ryanio** [comment]
we've discussed building fresh docs on release before, but it would be also be good to keep `master` updated to latest.

we could consider adding it as a husky pre-push cmd but then it would pollute PR diffs (unless people don't mind).

i could actually write a simple github action that runs docs:build on new commits to `master`, and can commit if there's a diff.

**Comment by evertonfraga** [comment]
Nice, I was just thinking about that lately, but haven’t reached an ideal solution yet. 

There are some things to take into consideration:

1) although convenient and cleaner, auto generate docs after merging to master is dangerous. We don’t want to lift branch protection for master for automated commits. 

2) Using automated docs commits on PRs feels better security-wise — we could always take a manual look before merging— but we’d have to have a mechanism not to flood the PR with up to one docs commit for each push to the branch. 

3) using husky solves the problems of 1 and 2, but pollutes git tree with scattered docs additions. 

I’d love to talk over that during this week :)

**Comment by holgerd77** [comment]
Was also thinking about that lately and I think I've found the solution [TM] here 😋 , thinking a bit from another angle.

I would suggest that we EthereumJS wide switch to a mode where we simply build **two version of the docs**, one into 'docs/master'  and one into 'docs/release' with the first one being continuously updated on PRs and reflect the latest `master` state and the second one just getting an update along a release PR.

This would need relatively simple adoptions on CI and just a simple rewrite on the README ("Have a a look at the latest [master](link) docs for an up-to-date `master` documentation or the [release](link) docs for documentation on the latest published release on npm" and otherwise wouldn't really cause any overhead.

It would also completely and cleanly solve this from a UX perspective, since this doc confusion by the user ("uh, this works differently when I install???") is haunting us for years now.

**Comment by holgerd77** [comment]
Have updated the branch here, this would need some reapproval then.

**Comment by ryanio** [comment]
looks like i was able to merge it in 👍

**Comment by evertonfraga** [comment]
GH repo settings says that reviews are dismissed when "reviewable commits" are in. It seems they're getting smarter — the merge had already reviewed commits 🔥

**Pull request merged**
