### PR TITLE
Add support for --data --gas --value command line arguments in state tests

### PR DESCRIPTION
**Pull request by jwasinger**
For specifying data, gas limit and value indices to use when running a state test

### CODE REVIEW

**Comment by axic** [comment]
Where is this used and what for?

**Comment by jwasinger** [comment]
It is being used in state test trace equivalence testing: https://github.com/holiman/evmlab/pull/10

**Comment by axic** [comment]
Can you go with long names? `--gas` `--data` `--value` ?

**Comment by jwasinger** [comment]
Sure. that's reasonable.

**Comment by jwasinger** [comment]
Made irrelevant by https://github.com/ethereumjs/ethereumjs-vm/pull/202

**Comment by jwasinger** [comment]
I've changed my mind.  This could be a useful addition to state tests and the code is already in place.

**Comment by holgerd77** [comment]
I'm also not getting the whole picture here and also not really getting, how this is used (can you also add a line to the README here?). Is this also channeled through ``ethereumjs-testing``? Or is the counterpart somewhere else?

**Comment by jwasinger** [comment]
Yeah.  I will add some info to the README.  The use case for this is to be able to debug a single test case in a test which contains more than one.  Example: https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stBadOpcode/badOpcodes.json#L6629-L6750

So, to run a single one of these cases, the command would be `node tests/tester.js -s --data {index}`

**Pull request merged**
