### PR TITLE
Tooling optimization

### LINKED ISSUE #773: Coverage result improvements for PRs
These are the three workflows for the VM tests, from [this sample run](https://github.com/ethereumjs/ethereumjs-vm/runs/762586200?check_suite_focus=true):

| job | duration |
|------------|--------|
| State      | 29 min |
| Blockchain | 14 min |
| API        | 7 min  |

The coverage tests (7 min) are run within `State` job, totaling a whopping 29min. I will move it to the API job, so durations are more balanced.

**Why this is bad:**
1. Half hour to get test results is _plain_ bad.
1. **Risk of (temporary) false negative:** Codecov waits for all jobs to complete, so it can generate the merged report and notify GitHub with the results. When a job takes so long to complete, it reaches Codecov's timeout, and generates a wrong report that does not consider VM coverage. This leads to false negative (coverage failure) until VM tests finish and proper data is sent back to Codecov to amend.

Example: 
Here, the coverage results are posted before VM tests finish. This is a false negative and we should avoid it.

image

### PR DESCRIPTION
**Pull request by evertonfraga**
This PR tackles three requirements at once:
1. CI performance optimizations
1. with simpler, faster experience for developers
1. keeping the CI workflows as simple as possible

---

image
_Rainbow-like output of Lerna commands running in parallel._

- [x] Parallelizes husky pre-push linting hook, saving ~60% of time.
- [x] Optimizes critical path for VM tests; prevents false negatives in code coverage (#773).
- [x] Makes use of the long-awaited github actions' default directory for the job. This helps us with a cleaner syntax for the jobs, without having to resort for Lerna for every command execution (#772). 
- [x] Gets rid of `npx` on CI jobs (#771).
- [x] Standardizes .gitignore across packages
- [x] Allows package-lock.json
- [x] Normalizes all dependencies' versions (#782)
- [x] Uses Lerna hoist
- [x] Caches node modules with one cache per package (with varying sizes)
- [x] Fixes linting differences

**Critical path to Codecov upload now 67% faster**

| before | after |
|------|----|
| 22m 18s | 7m 19s |

**Jobs run 54% faster in average, critical path ~48% faster**

|               | before  | after   | change |
|---------------|---------|---------|--------|
| account       | 1m 33s  | 26s     | -72%   |
| block         | 5m 17s  | 1m 35s  | -70%   |
| blockchain    | 3m 48s  | 1m 1s   | -73%   |
| common        | 1m 36s  | 25s     | -74%   |
| ethash        | 4m 41s  | 1m 29s  | -68%   |
| tx            | 4m 16s  | 1m 18s  | -70%   |
| vm:api        | 6m 55s  | 8m 52s  | +28%   |
| vm:blockchain | 12m 2s  | 7m 32s  | -37%   |
| vm:state      | 24m 10s | **12m 35s** | -48%  <= bottleneck |

### CODE REVIEW

**Comment by evertonfraga** [comment]
Work log: github cache loading and unpacking for all nested `node_modules` takes an impressive ~7m of execution, with a 1634MB bundle size. This highlights the need of package hoisting, which was planned already. 

It might make sense to try some more things:
a) create one cache entry per package. this will certainly take some load off from "leaf" packages, like `ethash`, `common` and `account`.
b) use caching only for specific jobs, and perform scoped bootstrap during CI run.

**Comment by evertonfraga** [comment]
Work log: 
Using `lerna --hoist` decreased overall bundle size from 1.6GB to 1.1GB. Still, 
ethereumjs-testing represents 83% of the node_modules final size (900MB). My conclusion is that it's not worth to share this cache among the 7 packages, given that only the VM uses `ethereumjs-testing`.

- [ ] Back to scoped installation & build (only package being tested and dependencies)
- [ ] Split cache keys, earmarking it with their package names

**Comment by holgerd77** [comment]
@evertonfraga yeah, that seems to make sense regarding the `ethereumjs-testing` size, thanks for digging into these setup things so thoroughly! 👍

**Comment by evertonfraga** [comment]
This is now ready for review. Further additions will be added in following PRs.

**Pull request merged**
