### PR TITLE
[WIP] Fix browser test issues

### PR DESCRIPTION
**Pull request by s1na**
See #465.

### CODE REVIEW

**Comment by holgerd77** [comment]
Rebased this.

**Comment by holgerd77** [comment]
@s1na I've now fixed the index and blockchain test timeout issues by running against Goerli, do you think this is a legit fix? Can you generally review the code parts I added?

**Comment by holgerd77** [comment]
Because I was interested, results from coverage report just on the API tests:

Bildschirmfoto 2019-03-14 um 23 29 32

So this is a start, but not there yet either.

**Comment by s1na** [comment]
@holgerd77 that was a really interesting idea!

1. Does that fix the timeout because the goerli genesis state is smaller?
2. How does the coverage of API tests on goerli and mainnet compare? are they different?
3. I meant to also try to find why it is that generating canonical genesis is taking so much longer on browser than on node. Is that because of limited resources in the browser, or maybe that the database has a different implementation or different characteristics on browser? :thinking:

**Comment by holgerd77** [comment]
1. Yes
2. Coverage shouldn't be different, I also had the thought while working on this though that we at some point should test different chains (minimally: 2) within the API tests. I would suggest that we know stick to the Goerli version, eventually along the investigation you mentioned in 3) (makes very-much sense, yes, a bit strange the drop in performance and likely also has real-world implications for library usage) we can go more broadly. Does this make sense?

**Comment by s1na** [comment]
> we at some point should test different chains

I was just about to write the same!

Yes, that plan sounds good.

**Comment by holgerd77** [comment]
😀

Can you do an explicit short review of my code changes?

**Comment by s1na** [comment]
The changes look good, but I can't approve as I'm the PR author :smile:

**Pull request merged**
