### PR TITLE
Emit events before and after executing a message

### LINKED ISSUE #574: Events before and after executing a Message
I'm currently working in Solidity debugging tools using the VM, and I'm having a hard time getting the complete picture of what a tx does. This is because running a tx sometimes implies running multiple messages.

I need to construct something like this, but I think it's not possible right now:

```ts
interface MessageTrace {
  code: Buffer | number; // The bytecode or precompile number that the message executed
  value: BN;
  calldata: Buffer;
  returnData: Buffer;
  error?: VmError;
  steps: MessageTraceStep[];
}

type MessageTraceStep = MessageTrace | EvmStep;

interface EvmStep {
  pc: number;
  /* ... Anything obtainable from the VM's step event, I'm OK here */
}
```

Adding events on `beforeMessage` and `afterMessage` should be enough.

What do you think @s1na @holgerd77 ? Am I missing something?

I can prepare a PR for this if you agree.

### PR DESCRIPTION
**Pull request by alcuadrado**
This is a WIP PR, as I'm not sure about

1. Where to document this
2. Where to test it. Should I create a new file in `tests/api`?

Closes #574

### CODE REVIEW

**Comment by s1na** [comment]
> Where to document this

I just noticed we lack a comprehensive doc for the events. The API docs don't currently include the events. Should we maybe collect a list of the events in the README? Not sure where would be a good place for that.

> Where to test it. Should I create a new file in tests/api?

Hm, the easiest would probably be in the `GeneralStateTests` as they already run txes with multiple messages and already do listen to some events, e.g.:

https://github.com/ethereumjs/ethereumjs-vm/blob/c3d7a57971a54b91294f37cd5f9b329733d89740/tests/GeneralStateTestsRunner.js#L78

but on the other hand, those tests are rather a black-box and we don't know the expected result for each message in advance

**Comment by holgerd77** [comment]
Yes, events should really be documented (think we had some basic version before we switched to auto-generated docs, not sure?). Some are some [techniques](https://cancerberosgx.github.io/javascript-documentation-examples/examples/typedoc-tutorial-basic/docs/docco/src/index.html#events) to do this with documentation, but maybe for now some manual addition to README will also do as @s1na suggested?

For tests I would find this more fitting as a new file in `tests/api`.

Update: did a quick search and found e.g. [this](https://github.com/ethereumjs/ethereumjs-vm/commit/fafd74c289f591b9b8800ece69ccf6355a4a2698) on former event documentation, maybe we should simply do an adopted re-integration of the text in the README?

**Comment by holgerd77** [comment]
Hi @alcuadrado, will you be able to add some docs and tests on this soon, so that we eventually can include in a subsequent `v4.1.0` release (not too far away I think so that we incrementally get the Istanbul features out of the door and people can test)? Or shouldn't we wait for this and release independently?

**Comment by alcuadrado** [comment]
I added tests for all of the events in this PR, and added documentation about them in the README.

**Comment by alcuadrado** [comment]
Oops, this was outdated wrt master. I rebased it.

**Comment by holgerd77** [comment]
@s1na @alcuadrado I would now prepare release notes for a `v4.1` release on Thursday.

**Comment by alcuadrado** [comment]
Sounds good! Thanks

**Pull request merged**
