### PR TITLE
Runs tests with ts-node instead of node.

### PR DESCRIPTION
**Pull request by evertonfraga**
This PR aims to both kill some technical debt from the TypeScript migration and normalize how tests are run, in preparation for the monorepo migration. This way we won't need to move dist files across CI builds.

The sentence below can still be found in our documentation, although after the TypeScript migration that wasn't possible anymore:
`Tests run against source by default. They can be run with the --dist flag`

@holgerd77 The API test runners are all hardcoded to require from `dist/`. With your OK, I can make it work just like `blockchain` and `state` tests: testing against the source by default and against `dist/` using `--dist`.

### CODE REVIEW

**Comment by holgerd77** [comment]
@evertonfraga Yes, running on `dist/` was a left-over from the `TypeScript` migration process, see comment [here](https://github.com/ethereumjs/ethereumjs-vm/pull/495#issue-269548798). This can be reverted.

**Comment by evertonfraga** [comment]
Great! I will proceed with these changes. Thanks.

**Comment by holgerd77** [comment]
@evertonfraga Ah, this is likely up again for review? Procedural note: better to just place another comment on stuff like this since GitHub is just not notifying on removing labels or stuff, then this is likely to be overlooked.

Have updated the branch and will do a review and eventually merge once tests are through again.

**Comment by evertonfraga** [comment]
Right, thanks!

There'll be a second step to this category of changes, which will completely remove `require(../../dist)` from tests. This does not seem crucial to the migration, so I put on hold for a bit.

Example: https://github.com/ethereumjs/ethereumjs-vm/search?q=require+dist&unscoped_q=require+dist

**Comment by holgerd77** [comment]
@evertonfraga ok

**Pull request merged**
