### PR TITLE
Avoid double-callbacks in CALL

### PR DESCRIPTION
**Pull request by axic**
This fixes test case `Call50000_identity`.

### CODE REVIEW

**Comment by axic** [comment]
Explanation: the actual call is moved into the successful-case of `accountIsEmpty`. The way to trigger two callbacks is if the account is empty and thus newAccountGas applies, but deducting that trigger and OOG. In this case the actual call still happens resulting in a double callback.

**Comment by axic** [comment]
This change also enables turning back on a lot of tests, the skip list would need to be reduced to
```
const skip = [
  'CALLCODE_Bounds', // Uses >270Mb of memory
  'CALL_Bounds', // Uses >270Mb of memory
  'CREATE_Bounds', // Uses >270Mb of memory
  'DELEGATECALL_Bounds', // Uses >270Mb of memory
  'mload32bitBound_return2', // Uses too much memory
  'RevertDepthCreateAddressCollision', // test case is wrong
]
```

**Comment by axic** [comment]
@jwasinger @holgerd77 @cdetrio anybody merging this? :)

**Comment by holgerd77** [comment]
@axic I though that there is an ``in progress`` label attached, therefore I waited, has this some other meaning than the ``[WIP]`` pre-string?

**Comment by axic** [comment]
@holgerd77 I don't know how that label ended up there, but no, this is finished.

**Comment by axic** [comment]
@holgerd77 done

**Pull request merged**
