### PR TITLE
Transition VM tests to TypeScript

### PR DESCRIPTION
**Pull request by holgerd77**
This PR transitions the VM test suite to TypeScript. State and blockchain tests are converted, API tests partially. First thought we could merge this partial API test transtion state cause the `test:API` command runs with both js and ts files but then realized that the `test:API:browser` command fails and it is probably easier to convert all the API tests as well and then adopt the Karma config and not introduce some hybrid setup.

I will (likely) stop on this for now. If you want to continue here feel free to do so, then please announce here before on what files you will be working and don't push directly on the branch but open a separate PR towards this branch.

### CODE REVIEW

**Comment by holgerd77** [comment]
Note: this is now also getting under the reign of the linter, therefore there are more changes than the manual ones along the transition.

**Comment by jochem-brouwer** [comment]
Have glanced over it, will have to take a deeper look later. I also love that tests are now being linted! 😄

**Comment by ryanio** [comment]
woo thanks for starting this!

it looks like `tests/api/EIPs/EIP2537-BLS-tests.js` was erroring out with `Cannot find module '../../util'` since it was converted to ts, so i converted that file for now and can do some more conversion work in a separate PR as you suggested. 

in working on that file I noticed that the `vm.runCall` opts are all taken in as `Buffer`s so that would be some good future work to update them to better types (Address, BN, etc.)

i also updated the `coverage:test` script to accept ts

**Comment by evertonfraga** [comment]
That's great! :D

As a following step, maybe we can keep a bare minimum of JS tests, to ensure the behavior of the API in the JS world. I realized how important this was when we had the discussion of `undefined` vs. `null` when instantiating classes. In the TS world it wouldn't compile, and in JS it would create a class with a weird state, with high risk of bugs down the road.

**Comment by ryanio** [comment]
@evertonfraga that's a good idea, hm ok i was thinking of fully transitioning over to karma-typescript from karma-browserify but in that case if we want to keep some sanity JS tests we can probably use `allowJs: true`

**Review by ryanio — DISMISSED** [review]
ok, this looks good to me now!

**Review by ryanio — APPROVED** [review]

**Review by holgerd77 — COMMENTED** [review]
Woah, unbelievable PR, you really can't stop once you started, right? 😂

😁😄😆

Really great, will merge.

**Comment by jochem-brouwer** [comment]
Love this PR and the lighting speed it was written!! 😍

**Pull request merged**
