### PR TITLE
Run blockchain tests

### PR DESCRIPTION
**Pull request by holgerd77**
This is now finally the usage of the mechanism running the blockchain tests on CircleCI by renaming the config files.

### CODE REVIEW

**Comment by Nathapon8899** [comment]
#341

**Comment by jwasinger** [comment]
@Nathapon8899  ?

**Comment by holgerd77** [comment]
Have retriggered a test run on VM ``e24909e`` latest commit on ``master``, ``ethereumjs-testing`` ``v1.2.4``.

**Comment by holgerd77** [comment]
Result blockchain tests:

```shell
1..848
# tests 848
# pass  526
# fail  322
```

Too much.

**Comment by holgerd77** [comment]
Many of the failures above seem difficulty related. I tested:

```shell
node ./tests/tester.js -b --test='notxs_Byzantium'
```

This fails with ``Error: invalid POW``, thrown from within the blockchain class and can be made explicit (normally hidden) by adding ``console.log(err)`` in the ``BlockchainTestRunner.js`` test class after ``blockchain.putBlock()`` (respectively in the callback).

This doesn't necessarily mean that the latest updates from the blockchain or block classes have introduced an error. There were lately various discussions about wrong difficulty values in the blockchain tests on tests Gitter, maybe these test cases are wrong (one could compare with an older snapshot blockchain test from ``ethereumjs-testing``). I have also tested directly within ``ethereumjs-block`` in the ``node_modules`` folder, ``byzantium`` hardfork setting is passed correctly and the difficulty tests are all passing if one goes to the repo and checks.

**Comment by holgerd77** [comment]
Have filed an issue here: https://github.com/ethereum/tests/issues/530

**Comment by holgerd77** [comment]
Retriggered a test run after merging of https://github.com/ethereumjs/ethereumjs-vm/pull/373, also to get an impression about changes in blockchain test run time after introduction of ``sealEngine`` usage (things should speed up).

**Comment by holgerd77** [comment]
Ok, this is now back to "normal" 60 failing tests (actually 6 less than before), see also https://github.com/ethereumjs/ethereumjs-vm/issues/338 for comparison and context, some results:

```shell
1..848
# tests 848
# pass  788
# fail  60
```

Execution speed of test run on CircleCI is now down to a whopping 12:39 min, which is fantastic since this means we can now (after getting test failures down) run this on every PR CI run!!! :sparkles: 😄

**Comment by holgerd77** [comment]
Now obsolete to run periodic blockchain test runs through merging of  https://github.com/ethereumjs/ethereumjs-vm/pull/374.

**Pull request closed without merging**
