### PR TITLE
Update labeler.yml

### PR DESCRIPTION
**Pull request by evertonfraga**
Fixes paths so it matches those for the monorepo structure. Reference: https://github.com/evertonfraga/ethereumjs-vm/tree/master/packages

### CODE REVIEW

**Comment by holgerd77** [comment]
@evertonfraga Same question as for @ryanio on his account library PR: should I generally (respectively in most cases where I don't see some reasoning against) merge a PR after review or better to just approve and leave merging to you?

**Comment by holgerd77** [comment]
(side note: Ryan already approved but had to re-approve after merging in the changes from `master`)

**Comment by evertonfraga** [comment]
Right, 

I'd like to make use of the label combo `pr: please review` + `pr: merge ready` for PRs that can be merged right away after review. Otherwise, just approving is good. :)

**Comment by holgerd77** [comment]
Ah, though I once introduced the labels throughout the last year I actually wasn't aware any more that we have this "merge ready" label. 😋 This is actually a nice and clean solution, maybe we can generally get this established a bit. Will try to apply this myself.

**Pull request merged**
