### PR TITLE
Print state root after transaction completion when --jsontrace is specified

### PR DESCRIPTION
**Pull request by jwasinger**
See: https://github.com/ethereum/tests/issues/249

### CODE REVIEW

**Comment by holgerd77** [comment]
There is a ``t.comment`` function I also recently discovered in ``tape`` like [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/tester.js#L210) for custom test output to the console, can we try to consistently use this instead of ``console.log`` (maybe also change the other occurrences through this PR)?

This gives a more consistent output stream e.g. for channeling the output to another stdout or using custom stream reporters for tape (https://github.com/substack/tape#var-stream--testcreatestreamopts).

**Comment by holgerd77** [comment]
(one more background common on this: experimented with stream reporters couple of weeks ago, think it would be nice to be a bit more flexible on test output, e.g. to leave all the success cases output when most of the tests pass).

**Comment by jwasinger** [comment]
Cool find!

**Comment by axic** [comment]
Is something blocking the merge of this?

**Comment by jwasinger** [comment]
Nope.  please review and merge if you get a chance.

**Comment by holgerd77** [comment]
@jwasinger Can you use the ``t.comment`` function for this as we discussed above?

**Pull request merged**
