### PR TITLE
Convert Bloom to es6 class

### PR DESCRIPTION
**Pull request by s1na**
Converts Bloom to an es6 class, and moves it to a directory to have it as a separate module.

My thinking is to structure the VM as multiple modules which contain most of the code, and in the root directory (`lib/`) have code that connects these individual modules together. This should also ease our way into a monorepo (if we decided to go for it). Bloom was a low-hanging fruit, I'll create an issue to discuss how to structure the rest of the code.

Bloom is used only internally, and is not exposed, so this shouldn't be a breaking change.

### CODE REVIEW

**Comment by holgerd77** [comment]
The bloom file here is also showing as deleted + new file, can you change that for review? If you did renaming via git maybe you have to do it in two steps like:

1. `bloom.js`-> `bloom/bloom.js`
2. `bloom/bloom.js` -> `bloom/index.js`

? Just an idea, have absolutely no confirmation if this would work better.

**Comment by holgerd77** [comment]
(and if so probably accompanied by two separate renaming commits for GitHub to process)

**Comment by s1na** [comment]
Yeah this is a big issue, I have to find a fix. Maybe I'm doing something wrong in my work flow. I re-worked the commit history and even though the first [commit](https://github.com/ethereumjs/ethereumjs-vm/pull/428/commits/08f66768308306ed2411adbccec7897eb592948c) clearly shows this is only a rename, but it's still being shown as a removed file and an added file... Should I do it in two PRs?

**Comment by holgerd77** [comment]
Can/did you try to do it in two steps like I suggested above and do one commit per step (so first commit just for directory move, second commit for file renaming)? Maybe this becomes easier for GitHub to process?

**Comment by holgerd77** [comment]
Found this similar problem description https://github.com/gogs/gogs/issues/5056.

Also points in the direction that the suggestion above could eventually fix this.

**Comment by holgerd77** [comment]
Ok, have reviewed and merged.

**Pull request merged**
