### PR TITLE
State manager API changes

### PR DESCRIPTION
**Pull request by mattdean-digicatapult**
This is to inform discussion of #268 as requested in that thread, but is not intended to be merged in it's current state.

### CODE REVIEW

**Comment by holgerd77** [comment]
Oh, the state tests are actually passing on this? That’s already impressive, cool!

**Comment by mattdean-digicatapult** [comment]
I think all the necessary tests should be passing, with the cache tests being commented out as the exception. Honestly I had to make my changes that way in order to make sure what I was doing was even viable. Not sure what's going on with the Travis build, but I'm pretty sure my changes aren't at fault

**Comment by axic** [comment]
Sorry for that but since #266 was merged, this needs to be rebased.

**Comment by mattdean-digicatapult** [comment]
Thanks @axic, I've rebased and everything still seems to work. A few of the changes from #266 seemed to conflict in direct opposition to my changes, notably in the moving of the `blockchain` instance onto `stateManager` from the `vm`. I've stuck with my way for reasons discussed in #268, but I think it would be good to work out where the `blockchain` should sit so that we're not trampling on each others changes.

**Comment by axic** [comment]
I think to speed up the process of merging this we need to split it into smaller chunks. I can see one good first step is prefixing the soon-to-be-private variables with underscore (`_cache`, `_trie`) in a separate PR.

**Comment by mattdean-digicatapult** [comment]
Unquestionably this needs splitting up before it can be merged. My intention with this PR was really just to facilitate the discussion in #268. If others are happy with the logic I presented there I'm more than happy to start breaking this up into separate PRs.

**Comment by holgerd77** [comment]
Hi @mattdean-digicatapult, have sent you a message on Gitter which is time-critical, hijacking this thread to notify you on a second communcation means! 😄

**Comment by mattdean-digicatapult** [comment]
These changes have all now been merged to master. Closing

**Pull request closed without merging**
