### PR TITLE
Reset selfdestruct on revert

### PR DESCRIPTION
**Pull request by mattdean-digicatapult**
Fixes test TouchToEmptyAccountRevert3 on Constantinople.

Once #326 is merged this should mean all the tests now pass 🎉

### CODE REVIEW

**Comment by mattdean-digicatapult** [comment]
Noooooo, I thought I had it. Will check, thanks @rmeissner

**Comment by mattdean-digicatapult** [comment]
Hang on @rmeissner, how did you get a failure? I've just replayed this commit on top of the eip-1052 branch and I'm getting no failures

**Comment by rmeissner** [comment]
I looked at the results of the ci: https://circleci.com/gh/ethereumjs/ethereumjs-vm/3060?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mattdean-digicatapult** [comment]
So there's 14 failures for that build and 15 for master https://circleci.com/gh/ethereumjs/ethereumjs-vm/3012. The difference being the 14 fixed in #326 right?

**Comment by rmeissner** [comment]
Ahh I forgot that EXTCODEHASH was not merged :D .... so yeah we have ... all tests should be fixed if both PRs are merged :D

**Comment by mattdean-digicatapult** [comment]
Awesome, more than happy BTW to rebase this on top of the merged EXTCODEHASH changes and get the first fully passing build in a long time

**Comment by holgerd77** [comment]
Just merged EXTCODEHASH. 😄

**Comment by mattdean-digicatapult** [comment]
rebased, sorry @holgerd77

**Comment by rmeissner** [comment]
WOHOOOOO all tests pass gz @mattdean-digicatapult @holgerd77

**Comment by holgerd77** [comment]
Whew, that was a long way.

Congrats, everyone!!!

**Pull request merged**
