### PR TITLE
Testing package upload to github artifacts

### PR DESCRIPTION
**Pull request by evertonfraga**
This is a test being made by @cgewecke and I.

The goal is to have a URL of an installable package by the end of each job.

### CODE REVIEW

**Comment by evertonfraga** [comment]
Artifact uploaded: https://github.com/ethereumjs/ethereumjs-vm/suites/1263193423/artifacts/19365698

**Comment by evertonfraga** [comment]
GH requires an api key for artifacts, even in public repos.

image

**Comment by evertonfraga** [comment]
@ryanio thanks! sorry, I always confuse this word: artefato 🇧🇷 ≠ 🇺🇸 artifact

**Comment by holgerd77** [comment]
Funny, seems to be the PR of typo corrections, I had another one - was so irritated by "an URL" in the initial text that I couldn't resists and [google](https://whatis.techtarget.com/feature/Which-is-correct-a-URL-or-an-URL) this and finally corrected (tldr; it's "a URL"). 😝  🤪

**Comment by cgewecke** [comment]
Just an update from the meeting this morning:

I've experimented with bundling the VM in a way that honors the monorepo symlinks at a given commit
+ generating a vanilla JS artifact is quite simple - have a webpack config that works 
+ generating `.d.ts` files that are valid for this bundle is more complex - could not find a straightforward way of walking the dependency tree and collecting all the typedefs across packages and exposing them so that the bundle is TS friendly. 

After some discussion @holger and I both thought that this effort might *not* be worth pursuing and that it's more straightforward to manually execute developer releases in the few cases where there's a PR we'd like to experiment with out in the real world than to invest a lot of time automating here...

@ev WDYT?

**Comment by evertonfraga** [comment]
@cgewecke OK, let's bet on easing the test and execution of those libraries locally, with Verdaccio: https://github.com/ethereumjs/ethereumjs-vm/blob/939eb12b77836792d0ed2a355ccafb8acd9bae86/README.md#testing-packages-locally-on-other-projects

**Pull request closed without merging**
